### ISSUE TITLE
Error on MergeToCheckpoint (not enough values to unpack (expected 2, got 1))

### ISSUE THREAD

**Issue by marcuspflanz** [hako-mikan/sd-webui-supermerger#10]
Hey,

great plugin! :)

When trying to merge a Lora with a Checkpoint into a new checkpoint I get error below with some Loras.

Any idea why this happens with some Loras while others work just fine?

> merging... [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
> Traceback (most recent call last):
>   ...
>   File "/content/gdrive/MyDrive/sd/stable-diffusion-webui/extensions/sd-webui-supermerger/scripts/mergers/pluslora.py", line 338, in pluslora
>     msd_key, lora_key = fullkey.split(".", 1)
> ValueError: not enough values to unpack (expected 2, got 1)

**Comment by marcuspflanz** [comment]
ah sorry - my failure.
Tried to handle a textual inversion file as a lora >.<

**Comment by phucbienvan** [comment]
I also encountered a similar error, if you used 2 Loras, how did you fix it?
