### ISSUE TITLE
Saving multiline elemental mergings

### ISSUE THREAD

**Issue by miasik** [hako-mikan/sd-webui-supermerger#100]
I prefer using multi-line list of elements. Short and simple example:
IN00::0.5
M00::0.125
OUT04::0.3
Such lists can be much longer and working with them this way is really convenient for me. It works, but it has some disadvantages.
1. Each merge adds its amount of lines to merges counter. For the example above, it adds 3. If my previous run has its number 100, the next number is 103 instead of 101. More lines in a recipe means more increasing for the counter by one merging.
2. Restoring such recipe by its number returns an error or restores only the first line of the recipe.
Hope you can help to manage with these disadvantaged.

**Comment by hako-mikan** [comment]
So you're saying it's better to separate them by a blank line?
When there are many elements to be specified, it is certainly easier to read if there is a line break. I will try to fix it, but this kind of modification takes time to test, so please wait a bit.

**Comment by miasik** [comment]
Nonono!
Something wrong in my explanation, sorry.
I'm writing not about the delimiter/separator. It works as I expect during merges and useful for me to work with it. It's OK for me to keep it as-is. 

The point is in saving.
Look at the numbers. It adds more than +1 for one merge.
Its OK to see recipes with our eyes and then copy and paste manually, but Supermerger fails loading such recipes from the file by its number.
![изображение](https://github.com/hako-mikan/sd-webui-supermerger/assets/1073832/96b14865-adaa-4e58-bcab-e27b62fd95b5)

**Comment by hako-mikan** [comment]
OK, I understand. I'll take a look.

**Comment by hako-mikan** [comment]
Fixed.
