### ISSUE TITLE
Wrong number of mergings

### ISSUE THREAD

**Issue by miasik** [hako-mikan/sd-webui-supermerger#104]
I wanted to use different SIDs for elemental merging and filled x/y plot this way. I expected that supermerger would have done one merging and ten(amount of SIDs) renders. Instead of that supermerger did the same merging for each SID. Is it OK?
Also, there is an error each X/Y run(at the bottom) during saving the final grid.

![изображение](https://github.com/hako-mikan/sd-webui-supermerger/assets/1073832/30ca76df-fc38-4fcf-ac0d-9dc8c67178b2)

> XY plot start, mode:Weight sum:A*(1-alpha)+B*alpha, X: elemental, Y: seed, MBW: True███| 30/30 [00:25<00:00,  1.42it/s]
xmen:cond_stage_model.transformer.text_model.embeddings::1, ymen:1841429933, 1841429939, 1554818056, 1554818058, 1554818063, 2071156733, 2071156734, 2071156739, 3890708676, 1950996774, xtype:elemental, ytype:seed, weights_a:0, weights_b:0, model_A:instagram-v6e1_50000.fp16.fixed.safetensors [24de7ef270],model_B :Anime\Yoh-cosA-055-Hass.fp16.safetensors [bf603f9906], model_C:, alpha:0.875,        beta :0.25, mode:Weight sum:A*(1-alpha)+B*alpha, blocks:True
['1841429933', '1841429939', '1554818056', '1554818058', '1554818063', '2071156733', '2071156734', '2071156739', '3890708676', '1950996774']
the die was thrown : ['1841429933', '1841429939', '1554818056', '1554818058', '1554818063', '2071156733', '2071156734', '2071156739', '3890708676', '1950996774']
XY plot: X: elemental, cond_stage_model.transformer.text_model.embeddings::1, Y: seed, 1841429933 (1/10)
  model A       : instagram-v6e1_50000.fp16.fixed
  model B       : Anime_Yoh-cosA-055-Hass.fp16
  model C       :
  alpha,beta    : (1.0, 0.25)
  weights_alpha : [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.1, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
  weights_beta  : 0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2
  mode          : Weight sum:A*(1-alpha)+B*alpha
  MBW           : True
  CalcMode      : cosineA
  Elemental     : ['cond_stage_model.transformer.text_model.embeddings::1']
  Tensors       :
Loading weights [bf603f9906] from E:\SD\automatic1111\models\Stable-diffusion\Anime\Yoh-cosA-055-Hass.fp16.safetensors
Creating model from config: E:\SD\automatic1111\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: cached vae.ft.mse.84.fp16.fixed.pt
Applying optimization: sdp-no-mem... done.
Model loaded in 8.0s (load weights from disk: 0.5s, create model: 0.5s, apply weights to model: 5.8s, apply half(): 0.4s, move model to device: 0.7s).
Loading weights [Anime_Yoh-cosA-055-Hass.fp16] from cache
Loading weights [24de7ef270] from E:\SD\automatic1111\models\Stable-diffusion\instagram-v6e1_50000.fp16.fixed.safetensors
Creating model from config: E:\SD\automatic1111\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: cached vae.ft.mse.84.fp16.fixed.pt
Applying optimization: sdp-no-mem... done.
Model loaded in 7.9s (load weights from disk: 0.4s, create model: 0.5s, apply weights to model: 5.6s, apply half(): 0.4s, load VAE: 0.1s, move model to device: 0.8s).
Loading weights [instagram-v6e1_50000.fp16.fixed] from cache
Stage 0/2: 100%|██████████████████████████████████████████████████████████████████| 1143/1143 [00:09<00:00, 123.20it/s]
Stage 1/2:  60%|████████████████████████████████████████                           | 684/1143 [00:12<00:03, 147.15it/s]['cond_stage_model.transformer.text_model.embeddings'] [''] cond_stage_model.transformer.text_model.embeddings.token_embedding.weight 1.0
Stage 1/2:  83%|███████████████████████████████████████████████████████▌           | 948/1143 [00:13<00:00, 332.75it/s]['cond_stage_model.transformer.text_model.embeddings'] [''] cond_stage_model.transformer.text_model.embeddings.position_embedding.weight 1.0
Stage 1/2: 100%|███████████████████████████████████████████████████████████████████| 1143/1143 [00:14<00:00, 76.36it/s]
Stage 2/2: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1143/1143 [00:00<00:00, 1146088.81it/s]
Applying optimization: sdp-no-mem... done.
Loading VAE weights specified in settings: cached vae.ft.mse.84.fp16.fixed.pt
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:05<00:00,  2.72it/s]
XY plot: X: elemental, cond_stage_model.transformer.text_model.embeddings::1, Y: seed, 1841429939 (2/10)████████████████████████████████████████████████████████████| 15/15 [00:04<00:00,  3.97it/s]
  model A       : instagram-v6e1_50000.fp16.fixed
  model B       : Anime_Yoh-cosA-055-Hass.fp16
  model C       :
  alpha,beta    : (1.0, 0.25)
  weights_alpha : [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.1, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
  weights_beta  : 0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2
  mode          : Weight sum:A*(1-alpha)+B*alpha
  MBW           : True
  CalcMode      : cosineA
  Elemental     : ['cond_stage_model.transformer.text_model.embeddings::1']
  Tensors       :
Loading weights [Anime_Yoh-cosA-055-Hass.fp16] from cache
Loading weights [instagram-v6e1_50000.fp16.fixed] from cache
Stage 0/2: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1143/1143 [00:10<00:00, 108.77it/s]
Stage 1/2:  60%|██████████████████████████████████████████████████████████████████████████████████████                                                          | 683/1143 [00:15<00:04, 113.41it/s]['cond_stage_model.transformer.text_model.embeddings'] [''] cond_stage_model.transformer.text_model.embeddings.token_embedding.weight 1.0
Stage 1/2:  83%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                        | 948/1143 [00:16<00:00, 215.78it/s]['cond_stage_model.transformer.text_model.embeddings'] [''] cond_stage_model.transformer.text_model.embeddings.position_embedding.weight 1.0
Stage 1/2: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1143/1143 [00:18<00:00, 61.51it/s]
Stage 2/2: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1143/1143 [00:00<?, ?it/s]
Applying optimization: sdp-no-mem... done.
Loading VAE weights specified in settings: cached vae.ft.mse.84.fp16.fixed.pt
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:05<00:00,  2.63it/s]

...

> XY plot: X: elemental, cond_stage_model.transformer.text_model.embeddings::1, Y: seed, 1950996774 (10/10)
>   model A       : instagram-v6e1_50000.fp16.fixed
>   model B       : Anime_Yoh-cosA-055-Hass.fp16
>   model C       :
>   alpha,beta    : (1.0, 0.25)
>   weights_alpha : [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.1, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
>   weights_beta  : 0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2
>   mode          : Weight sum:A*(1-alpha)+B*alpha
>   MBW           : True
>   CalcMode      : cosineA
>   Elemental     : ['cond_stage_model.transformer.text_model.embeddings::1']
>   Tensors       :
> Loading weights [Anime_Yoh-cosA-055-Hass.fp16] from cache
> Loading weights [instagram-v6e1_50000.fp16.fixed] from cache
> Stage 0/2: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1143/1143 [00:09<00:00, 121.29it/s]
> Stage 1/2:  59%|█████████████████████████████████████████████████████████████████████████████████████▋                                                          | 680/1143 [00:12<00:02, 166.76it/s]['cond_stage_model.transformer.text_model.embeddings'] [''] cond_stage_model.transformer.text_model.embeddings.token_embedding.weight 1.0
> Stage 1/2:  83%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▍                        | 948/1143 [00:12<00:00, 351.99it/s]['cond_stage_model.transformer.text_model.embeddings'] [''] cond_stage_model.transformer.text_model.embeddings.position_embedding.weight 1.0
> Stage 1/2: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1143/1143 [00:14<00:00, 77.84it/s]
> Stage 2/2: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1143/1143 [00:00<?, ?it/s]
> Applying optimization: sdp-no-mem... done.
> Loading VAE weights specified in settings: cached vae.ft.mse.84.fp16.fixed.pt
> 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:03<00:00,  4.12it/s]
> Error save prompt file[04:49,  3.77it/s]
> Traceback (most recent call last):
>   File "E:\SD\automatic1111\extensions\sd-dynamic-prompts\sd_dynamic_prompts\callbacks.py", line 24, in on_save
>     png_info = image_save_params.pnginfo["parameters"]
> KeyError: 'parameters'

**Comment by miasik** [comment]
@sverfier8807
You've done a lot for X/Y but here is something wrong :-)

**Comment by hako-mikan** [comment]
This is correct. As you pointed out, X is prioritized and therefore calculated each time. This can be avoided by setting the seed to X. There is no feature to automatically reduce calculation when the seed is selected, as in the web-ui's XY plot. (The web-ui's XY plot used to have a similar issue in the past.)

**Comment by miasik** [comment]
I'm trying to work with SID as X axis. It works much faster but it's sooo unconvinient :-(
Anyway, there is still an error at the end of X/Y:

> Error save prompt file [1:25:03,  4.70it/s]
> Traceback (most recent call last):
>   File "E:\SD\automatic1111\extensions\sd-dynamic-prompts\sd_dynamic_prompts\callbacks.py", line 24, in on_save
>     png_info = image_save_params.pnginfo["parameters"]
> KeyError: 'parameters

**Comment by hako-mikan** [comment]
It seems to be an error in dynamic prompts, but I am not concerned about it as it does not interfere with the operation at the moment.

**Comment by hako-mikan** [comment]
Anyway, you can swap XY now.
