### ISSUE TITLE
mergining lora keeps crashing it

### ISSUE THREAD

**Issue by Chasnet** [hako-mikan/sd-webui-supermerger#111]
Make lora it keeps crashing with this error
I don't know what to do
![111](https://github.com/hako-mikan/sd-webui-supermerger/assets/137001890/425c61f7-d4e1-4f90-b475-2200c67e597f)
![222](https://github.com/hako-mikan/sd-webui-supermerger/assets/137001890/dee7c745-f801-4aa4-bd86-39fb12710bf2)

**Comment by hako-mikan** [comment]
Downgrade the version of diffusers to 0.14 or lower.
https://github.com/hako-mikan/sd-webui-supermerger/discussions/52
#97
