### ISSUE TITLE
No way of saving settings to this line

### ISSUE THREAD

**Issue by ollobrains** [hako-mikan/sd-webui-supermerger#113]
Ok when merging LORA into a checkpoint the default values are 1.0 for this box "LoRAname1:ratio1:Blocks1,LoRAname2:ratio2:Blocks2,...(":blocks" is option, not necessary)" but if doing 10 or 20 LORAs it makes the end merge a sea of noise, ive found setting each individual one to 0.01 or 0.005 makes small incremental changes to the checkpoint model at hte end without destroying it.

Is it possible to have a option to set all the models checked for each merge the option to assign a bulk value, because if im doing 10-20 block merges at once its very time tedius to have to change each one individually, or even the option to save a value ?

**Comment by hako-mikan** [comment]
How about to use the text editor.
Copy textbox to text editor and replace ":1.0" to ":0.05" and paste to textbox.

**Comment by ollobrains** [comment]
that still leaves a lot of right clicking and copy paste for each LORA, my idea is a UI improvement and a way of speeding up the user experience and having less frustration.  I would imagine the coding time to make it happen would be very small.

I guess if you dont have the coding experience to make the change then thats fine ill perservre with it as is, its just very frustrating and ive seen a lot of comments on the stable diffusion subreddit from a lot of users saying the same thing.  One reason i came and raised it here

**Comment by hako-mikan** [comment]
Added.

**Comment by ollobrains** [comment]
😍

**Comment by ollobrains** [comment]
quick update after installing the update today, it still isnt appearing on the screen and now LORAs wont merge at all due to this error

" File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\routes.py", line 399, in run_predict
    output = await app.get_blocks().process_api(
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "C:\Users\xxx\Local\Programs\Python\Python310\lib\site-packages\gradio\blocks.py", line 1022, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\xxx\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 259, in pluslora
    filenames.append(c_lora.filename)
AttributeError: 'NoneType' object has no attribute 'filename'

**Comment by hako-mikan** [comment]
It seems something was missed.
Try again.
I have confirmed that it works.

**Comment by ollobrains** [comment]
ah thanks got it now, just had to update the UI and do a restart.  Thanks again
