### ISSUE TITLE
Diffusers version 

### ISSUE THREAD

**Issue by Eliont** [hako-mikan/sd-webui-supermerger#119]
Hello and good time of day.

```
  make LoRA start
  loading SD model : C:\SD\stable-diffusion-webui\models\Stable-diffusion\SD1.5.ckpt
  diffusers version :  0.17.1
  version of diffusers must be 0.10.2 to 0.14.0
```

WebUI version: [v1.3.2](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/baf6946e06249c5af9851c60171692c44ef633e0)  •  python: 3.10.6  •  torch: 2.0.1+cu118  •  xformers: 0.0.17  •  gradio: 3.32.0 

How to solve?

**Comment by hako-mikan** [comment]
downgrade the versions of diffusers.
You should search how to do it.
I cannot tell you because the way to downgrade diffusers is depending on environment.
This thread will help you.
https://github.com/hako-mikan/sd-webui-supermerger/discussions/52
