### ISSUE TITLE
Feature Request - Revert to last settings of previous merge & gen

### ISSUE THREAD

**Issue by RashanJS** [hako-mikan/sd-webui-supermerger#12]
It would be nice to have a revert to last settings button, for the previous merge & gen settings to be re-applied

Sometimes i don't know what MBW i changed last, by mistake, too many options. Overall, a simple button that retains n-1 settings would be easiest way to return previous MBW after multiple changes at last test run.

... Sorry if I did not notice if this is already a feature available in the extension, not sure where to find if so. This would be very useful to have. I would like to know.

BTW, thanks for this amazing tool.

**Comment by hako-mikan** [comment]
You can do that using "set from ID" button. If you input "-1" in "merge from ID" and press "set from ID" button. The last setting that you operated merge will be reverted. Past merge conditions can also be recalled: -2 is the second from the end, -3 is the third from the end, and so on.

**Comment by RashanJS** [comment]
Thanks for sharing this,  I had not idea how this worked. I figured there must be a way. Great!
