### ISSUE TITLE
SD-scriptsで作成したC3LierLoRAがLoConとして認識される

### ISSUE THREAD

**Issue by Yanagi-ai** [hako-mikan/sd-webui-supermerger#124]
【ISSUE】
SD-scriptsで作成したC3LierがLoConとして認識され､マージのエラーが発生します

【内容】
SD-scriptsで下記の設定で C3Lierを作成する際､network_argsの指定方法にconv_dimとconv_rankの表記ゆれがあります｡
画像のtest4はconv_dim=8で指定したもの､test5はconv_rank=8で指定したものです｡
![image](https://github.com/hako-mikan/sd-webui-supermerger/assets/117795546/3a4c842b-a534-4ee3-9a3e-b6e23c16b44a)

どちらもSD-scriptsの学習設定は同じですが､Supermerger上ではtest4はLoConとして認識され､test5はLoRAとして認識されているようです｡

【test4LoRAの設定】
```
network_module = "networks.lora"
network_args = [ "conv_dim=8", "conv_alpha=1", "argo=lora",]
```
【test5LoRAの設定】
```
network_module = "networks.lora"
network_args = [ "conv_rank=8", "conv_alpha=1", "argo=lora",]
```
SD-scriptsのReadmeでは､conv_dim表記で指定するよう説明されています｡
https://github.com/kohya-ss/sd-scripts/blob/c7fd336c5d5c0f05378dd34e7b5ca6ac8e972773/docs/train_network_README-ja.md?plain=1#L121

しかし､conv_dim指定で作成したLoRAの場合､Supermergerでのマージの際にエラーが発生します｡
![image](https://github.com/hako-mikan/sd-webui-supermerger/assets/117795546/6ae61f85-6425-480a-bfac-ecde15493eae)

一方でconv_rank指定で作成したLoRAの場合､エラーが発生せず正常にマージできます｡
![image](https://github.com/hako-mikan/sd-webui-supermerger/assets/117795546/a326b6e4-1209-43f6-a143-6e65f659d524)

この点の表記ゆれとエラーを発見したので､Issueとして提出させていただきます｡

**Comment by hako-mikan** [comment]
手元にC3LierLoRAがないので試せてないですが。
多分直ってるかと。
