### ISSUE TITLE
Sequential XY Broken / Corrupted result

### ISSUE THREAD

**Issue by Anashel-RPG** [hako-mikan/sd-webui-supermerger#128]
**Latest version of Auto1111 Vlad.** 

It's a little bit hard to describe but the result after last update looks like this:
![Broken](https://github.com/hako-mikan/sd-webui-supermerger/assets/36581141/ba243f1d-53a9-49fa-bf54-736ad19ebcc4) The result merged with other tools work well. Also, sequential XY used to work well before.

**Comment by hako-mikan** [comment]
Dose the last update mean this script? or Vlad?

**Comment by Anashel-RPG** [comment]
Hi! I made a latest git pull of both Vlad and Sequential extension.

**Comment by hako-mikan** [comment]
If you save the model in XY plot.
Is the model also broken?

**Comment by Anashel-RPG** [comment]
I think I found part of the answer: the prompt use by Sequential extension seem to have change. Before it used what I have set in the txt2images, but now it change some parameters:
`Prompt: <p class="plaintext">(rogue thief:1.2) wearing multiple layer (leather armor:1.2), (insanely detailed:1.5), ((solo)), (highest quality, Alessandro Casagrande, Greg Rutkowski, Sally Mann, concept art, 4k), (colourful), (high sharpness), ((detailed pupils)), red eyes, ((painting:1.1)), (digital painting:1.1), detailed face and eyes,Masterpiece, best quality, highly detailed photo:1, 8k, detailed face,photorealistic, (blonde curly Hair,ponytail hair cut, ecstatic:1.1),pale skin, (18yo woman:1),By jeremy mann, by sandra chevrier, by maciej kuciara, ((small Breast)),((samurai)), sharp, ((perfect body)), realistic, real shadow, 3d, ((white shirt)), ((leather skirt)), (silver sexy jewelerie), ((full body)), ((night city background)), (by Michelangelo)<br>
Negative prompt: flower, (bad art, low detail, pencil drawing, old, mature:1.6), (plain background, grainy, low quality, mutated hands and fingers:1.5), (watermark, thin lines:1.3), (deformed, signature:1.2), (big nipples, blurry, ugly, bad anatomy, extra limbs, undersaturated, low resolution), disfigured, deformations, out of frame, amputee, bad proportions, extra limb, missing limbs, distortion, floating limbs, out of frame, poorly drawn face, poorly drawn hands, text, malformed, error, missing fingers, cropped, jpeg artifacts, teeth, unsharp<br>
Steps: 20 | Sampler: PLMS | CFG scale: 6 | Seed: 2757312072 | Size: 512x512 | Model hash: a1c8f2906b | Model: 01-RPG-v5-itr40 | VAE: vae-ft-mse-840000-ema-pruned | Clip skip: 1 | Version: 0a49961 | Parser: A1111 parser</p>`

In this case, it switch the sampler from Euler to PLMS, the Steps from 75 to 20 and the CFG from 4.5 to 6. The rest of the prompt (Prompt, Negative and Seed) are correct.

**Comment by Anashel-RPG** [comment]
And no, the merged model is not broken, I was able to reproduce the broken image with the same parameter (PLMS @ 20 steps /w CFG 6) The image this produce look indeed like this.

**Comment by hako-mikan** [comment]
I see that Vlad's update has prevented some settings from being loaded from the txt2img tab. 
This may take some time to fix.

**Comment by Anashel-RPG** [comment]
No problem, thanks for the quick answer! 👍 Is there any way i can override theses settings in a panel from the extension perspective?

**Comment by hako-mikan** [comment]
Yes.
I plan to add setting panel to "Restore faces, Tiling, Hires. fix, Batch size" for Vlad users.

**Comment by Anashel-RPG** [comment]
The panel already exist (or is visible) for Vlad user. I meant the ability to overwrite the prompt / sampler / Steps and CFG (unless that's what you plan to add?). 

<img width="700" alt="Screenshot 2023-06-27 at 7 34 59 AM" src="https://github.com/hako-mikan/sd-webui-supermerger/assets/36581141/5cb3b368-e594-4327-8d90-8799199a758c">

**Comment by hako-mikan** [comment]
Year I plan to add "prompt / sampler / Steps and CFG" to "Restore faces, Tiling, Hires. fix, Batch size" panel.

**Comment by vladmandic** [comment]
> I see that Vlad's update has prevented some settings from being loaded from the txt2img tab.

can you elaborate on that?

**Comment by hako-mikan** [comment]
In this script, txt2img parameters load from txt2img tab using `txt2img_preview_params`.
I don't know why only prompt/negative prompt was loaded.

**Comment by vladmandic** [comment]
ah, ok, that explains the problem. `txt2img_preview_params` is not supposed to be used for that - its used for ti/hypernetwork training previews (e.g. images saved automatically every 500 iterations). and i've moved training to separate python modules.

**Comment by hako-mikan** [comment]
Year, I used it secretly.

**Comment by Anashel-RPG** [comment]
Do you know by any chance what version checkpoint I should rollback to in the meantime?

**Comment by hako-mikan** [comment]
Add settings. Try it.

@Anashel-RPG 
I don't know because I don't use Vlad.

**Comment by Anashel-RPG** [comment]
I get this error:
<img width="1008" alt="Screenshot 2023-06-28 at 12 43 49 PM" src="https://github.com/hako-mikan/sd-webui-supermerger/assets/36581141/61508ad9-d155-4761-a9a8-c2541ba1d972">

This is on latest https://github.com/vladmandic/automatic.git/tree/master
updated: 2023-06-28
hash: cccae902

For supermerger:
5e29503c
Wed Jun28

It does the merge but stop at after the 2 pass.

**Comment by Anashel-RPG** [comment]
Not sure why you closed it? I try to make the latest version run. It still does the same behavior (not getting the right parameters from text2image tab) and if you try to use the generation parameters, it give the following error:
<img width="959" alt="Screenshot 2023-06-29 at 9 57 27 PM" src="https://github.com/hako-mikan/sd-webui-supermerger/assets/36581141/92549ed7-59b9-430e-a04b-7f0d029e4c83">

**Comment by hako-mikan** [comment]
Thank you. It seems like there is another issue.

**Comment by hako-mikan** [comment]
Please let me know the results of this update. Also, tell me the name of the sampler you selected.

**Comment by Anashel-RPG** [comment]
DPM++ 2s a Karras, but I tested it extensively with other sampler and grid of 110+ combination and it work perfectly, not error after hours and hours of test. :) Thanks for fixing it!
