### ISSUE TITLE
List of LORA Modules loaded doesnt update when u

### ISSUE THREAD

**Issue by ollobrains** [hako-mikan/sd-webui-supermerger#131]
Ok so ive got 20 LORAs for merging into a checkpoint, once ive done that i tend to delete them, now if i go out of automatic1111 and delete them, then click update LORAs, the old ones arent deleted

If i go out and copy paste in another 20 to the list, and take the original 20 out it then generates a list of 40 (old ones that are deleted and the new ones)

Is there anyway of making sure that the list updates to reflect what is in the folder at the time of clicking update LORAs

**Comment by hako-mikan** [comment]
Updated.
"update list" button can delete deleted lora now.

**Comment by ollobrains** [comment]
ah yup it works thanks
