### ISSUE TITLE
Fix found for error since last update "TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'" when generating from SuperMerger tab

### ISSUE THREAD

**Issue by SwiftIllusion** [hako-mikan/sd-webui-supermerger#132]
In mergers.py, line 766
"    p.sampler_name = sd_samplers.samplers[sampler].name if s_sampler == 0 else sd_samplers.samplers[s_sampler-1].name"
That 0 is causing the error in the title when you try to generate from the SuperMerger tab.
Searched for solutions and found changing it to 'None' fixes it
"    p.sampler_name = sd_samplers.samplers[sampler].name if s_sampler == None else sd_samplers.samplers[s_sampler-1].name"

**Comment by hako-mikan** [comment]
Thanks. Fixed.
It seems that there was a fundamental bug in supermerger.py. Thank you.

**Comment by SwiftIllusion** [comment]
:) No worries, thank you.
Glad you were able to implement the fix with that in mind so soon, thanks a lot for that :) .
