### ISSUE TITLE
improvement: save button

### ISSUE THREAD

**Issue by zethfoxster** [hako-mikan/sd-webui-supermerger#143]
im doing a series of addsmooth and they take quite a bit of time to merge...once i settled on a good ratio, I check save box (as theres too many ugly merge ratios to save every single one)...but there is no "save current" button, so im forced to redo the exact merge i just did to save it.

**Comment by miasik** [comment]
There's a chance to get addsmooth faster because a commit #144 with multi-threading is in line.

**Comment by miasik** [comment]
#144 has already been merged. Update SM and test speed for addsmooth.
