### ISSUE TITLE
Error when merging lora to checkpoint ''Couldn't saved''

### ISSUE THREAD

**Issue by MK499** [hako-mikan/sd-webui-supermerger#149]
Hello, I tryed to merge a lora to a checkpoint, but when i do it i have this ''Error'' Couldn't saved, like the scripts don't know where to save it.
![Error4](https://github.com/hako-mikan/sd-webui-supermerger/assets/129749302/d08cca29-2892-4244-87ab-9e496f706c13)

How do i fix it ?

**Comment by hako-mikan** [comment]
Maybe your directory path include space or something wrong.

**Comment by MK499** [comment]
> Maybe your directory path include space or something wrong.

Well perhaps, Do you know where to fix it ? like in what files or scripts ?

**Comment by hako-mikan** [comment]
If there are spaces in the directory where web-ui is stored, delete them.

**Comment by MK499** [comment]
> If there are spaces in the directory where web-ui is stored, delete them.

I've checked webui-user.bat everything is normal no space at all, Also if you talk about webui.py or webui.bat well i checked too, but in these codes they are like 470+ Line (webui.py), I'm not sure what precise line i need to erase atm, like some have space but it's because it's the code.

Btw not sure if it's help, but the Base merger (Checkpoint Merger) that come with SD work fine with me.

**Comment by hako-mikan** [comment]
Where are the models created in the model manager outputted? It can be challenging to write to the C drive due to permission issues.

**Comment by MK499** [comment]
> Where are the models created in the model manager outputted? It can be challenging to write to the C drive due to permission issues.

Model manager ? Not sure what is it, but all my model's are saved at > stable-diffusion-webui\models\Stable-diffusion (The default directory) i didn't change anything.

For C: Drive Permissions, i'm the only user on my PC + I'm Admin in it so normally permissions is not a problem.

**Comment by hako-mikan** [comment]
Fixed to display the content of the error. 
Merge again after updating and let me know what the error is.

**Comment by MK499** [comment]
> Fixed to display the content of the error. Merge again after updating and let me know what the error is.

Here is the error: 
![Error44](https://github.com/hako-mikan/sd-webui-supermerger/assets/129749302/d17ee20e-c13f-42a5-bbab-3ce3da6eda63)

for the last line ''Le chemin d'accès spécifié est introuvable'' it's > ''The specified path was not found''

**Comment by hako-mikan** [comment]
I figured out the cause and have fixed it.

**Comment by MK499** [comment]
> I figured out the cause and have fixed it.

I just updated it and i have the same error as before: ERROR is Error while serializing: IoError(Os { code: 3, kind: NotFound, message: "Le chemin d’accès spécifié est introuvable." })

I will try later to reinstall completely SD, i'm wondering if something is corrupted or something.

**Comment by hako-mikan** [comment]
Oh I'm sorry. It's okay this time.

**Comment by MK499** [comment]
> Oh I'm sorry. It's okay this time.

I have the same error again but don't worry, i will try to do a fresh install of SD, i will update you.

**Comment by hako-mikan** [comment]
Is there any space in `Krx4AI` ?

**Comment by MK499** [comment]
> Is there any space in `Krx4AI` ?

Hello, sry for late reply i was busy.
The problem is solved now, when i updated. (Idk, perhaps somethings was wrong in the other commit).

Now it's good, Thx.

**Comment by MK499** [comment]
> Is there any space in `Krx4AI` ?

Hello, sry for late reply i was busy.
The problem is solved now, when i updated. (Idk, perhaps somethings was wrong in the other commit).
