### ISSUE TITLE
Auto results in error if different dimensions, instead of remaking dimensions

### ISSUE THREAD

**Issue by VikingUnleashed** [hako-mikan/sd-webui-supermerger#156]
Almost forgot: for whatever reason, the auto option in remake dimension just errors out with
"AssertionError: weights shape mismatch merging v1 and v2, different dims?"
Instead of remaking to appropriate dimension. Manually selecting the lowest common dimension avoids the error, but have to figure out lowest common dimension or just trial, error, and refresh your way to appropriate selection.

**Comment by hako-mikan** [comment]
fixed.
