### ISSUE TITLE
retained metadata when Merge LoRAs

### ISSUE THREAD

**Issue by toretate** [hako-mikan/sd-webui-supermerger#157]
LoRAをマージするときにメタデータを保持できないでしょうか？
（現在だとLoRAにWeightをマージしたり、LoRA同士をマージするときにメタデータが失われてます）

**Comment by toretate** [comment]
まだ不完全ですが、PR158 として出させてもらいました
https://github.com/hako-mikan/sd-webui-supermerger/pull/158

**Comment by hako-mikan** [comment]
ありがとうございます。
確かに消えてしまうのは不便でしたね。

**Comment by toretate** [comment]
マージありがとうございました
