### ISSUE TITLE
The extension doesn't appear

### ISSUE THREAD

**Issue by frugally9415** [hako-mikan/sd-webui-supermerger#16]
I've successfuly installed the extension, but it doesn't appear on my UI.
Scr: https://i.imgur.com/wv4qsgK.png

There is an execution error "ModuleNotFoundError: No module named 'lora'" on the command, what causes this?
I've also installed lora's extension on my web UI.

**Comment by hako-mikan** [comment]
This extension uses web-ui's LoRA functionality and will not work with older versions of web-ui. "extensions-builtin/Lora" is required.
