### ISSUE TITLE
'gbk' codec can't decode byte 0xaf in position 1669: illegal multibyte sequence

### ISSUE THREAD

**Issue by pzzmyc** [hako-mikan/sd-webui-supermerger#171]
![image](https://github.com/hako-mikan/sd-webui-supermerger/assets/43562427/2b5bfe98-18eb-4d44-9c4a-e6a2f563df3f)

**Comment by hako-mikan** [comment]
The error probably originates from the use of 2-byte characters, such as Chinese characters.
I believe it would be resolved by writing in English.

**Comment by pzzmyc** [comment]
> The error probably originates from the use of 2-byte characters, such as Chinese characters. I believe it would be resolved by writing in English.

Can you tell me roughly what went wrong, it doesn't seem to have any stages that use Chinese characters,include file paths, model file names, folders, or even no special characters, except for the webui translation

**Comment by pzzmyc** [comment]
June's old version worked fine
