### ISSUE TITLE
An issue with caching

### ISSUE THREAD

**Issue by miasik** [hako-mikan/sd-webui-supermerger#172]
Sorry, It's hard to explain.

Something happened after this commit https://github.com/hako-mikan/sd-webui-supermerger/commit/4f0a74939358d2efbef83eebf8ce99d43295879f.
Sometimes I see rows in XY grid looking the same or SM remembers the final result of a previous run and use it for the next run.
The commit above works well without any issues and as I see https://github.com/hako-mikan/sd-webui-supermerger/commit/9abc801c0f83e6977f8bdc0e1aad6bba75f1726a looks working too

**Comment by hako-mikan** [comment]
https://github.com/hako-mikan/sd-webui-supermerger/commit/4f0a74939358d2efbef83eebf8ce99d43295879f.
is 3 weeks ago 
https://github.com/hako-mikan/sd-webui-supermerger/commit/9abc801c0f83e6977f8bdc0e1aad6bba75f1726a
is 2 weeks ago 
So now, working well?
Or there is some problem still now?

**Comment by miasik** [comment]
> [4f0a749](https://github.com/hako-mikan/sd-webui-supermerger/commit/4f0a74939358d2efbef83eebf8ce99d43295879f). is 3 weeks ago [9abc801](https://github.com/hako-mikan/sd-webui-supermerger/commit/9abc801c0f83e6977f8bdc0e1aad6bba75f1726a) is 2 weeks ago So now, working well? Or there is some problem still now?

Sorry, I don't know when. I had a delay and faced into the bug two days ago. After I downgraded SM the error disappeared.

**Comment by hako-mikan** [comment]
may be fixed.

**Comment by miasik** [comment]
Looks like working now. Thank you!
