### ISSUE TITLE
SDXL model

### ISSUE THREAD

**Issue by kalle07** [hako-mikan/sd-webui-supermerger#176]
if i merge lorato SDXL it worked , ok so far !
but it always uses my VRAM full out of 16GB, and doesn't clear it afterwards !

**Comment by hako-mikan** [comment]
Its difficult to handle.
I changed code, but fixed or not is unclear.
try it.

**Comment by kalle07** [comment]
sry al ot of proofes not set !
if a field is empty, an error occurs that I see in the command, after that nothing can be done except restart automatic1111  ;)

**Comment by hako-mikan** [comment]
https://github.com/hako-mikan/sd-webui-supermerger/issues/200
Fixed.
