### ISSUE TITLE
[Feature Request] Automatically populate list for LoRa merging from prompt

### ISSUE THREAD

**Issue by Signorlimone** [hako-mikan/sd-webui-supermerger#179]
As per title, I'll try to better explain the feature request. 

Often I train LoRa with different block settings, then in A1111 I write a prompt and load more than one LoRa and adjust the weight until I'm satisfied with the results. Now I have to merge these LoRas with Supermerger, so I have to go into the extension, search for the LoRa to flag in the list (wich is pretty big in my case and searching it, even if they are in alphabetical order, is a long process), then I have to adjust the weights in the text list and then merge hoping to obtain a similar output that I had before with more than one LoRa.

My question: is there a way to implement a function that take the prompt from text2img and automatically put the LoRas used with the correct weight directly in supermerger LoRa tab? This will make everything easier, at least for me

Sorry to bother, hope my request doesn't sound unreasonable

**Comment by hako-mikan** [comment]
It might be difficult to implement immediately.
What I can say for now is that you don't need to choose from the list; you can directly enter the name "LoRA.
If it's entered in the prompt, couldn't you just remove the <> and execute what you want to do by copy and pasting?

**Comment by hako-mikan** [comment]
I've added a feature.
You can now load it using the "get from prompt" button.

**Comment by Signorlimone** [comment]
you are the absolute B E S T !
