### ISSUE TITLE
Can Loha support block merging operations

### ISSUE THREAD

**Issue by aftermath0703** [hako-mikan/sd-webui-supermerger#181]
I want to merge two Loha with certain block weight parameters, but I don't know how to do it. 
I tried to modify the code based on the implementation of the Lora merge function in the supermerger plugin, but only a single Loha can be implemented to modify the weight of each block. The merging effect of two or more Loha is very poor, it seems that there is a bug when adding weights to each layer. I don't know if this can be fixed.
Looking forward to a reply

**Comment by hako-mikan** [comment]
This script do not support block merging between LoHAs. However, block application is possible with LoHA alone. After applying block to each LoHA, you might be able to achieve what you want by merging using the tool from the LyCORIS author.
