### ISSUE TITLE
"The system can not find the path specified" 

### ISSUE THREAD

**Issue by filliptm** [hako-mikan/sd-webui-supermerger#184]
Getting this error when im merging a lora into a model

ERROR: Couldn't saved:C:\ai\New-Stable\stable-diffusion-webui\models\Stable-diffusion\sd_xl_base_1.0+Lster-XL-V1-000015.fp16.safetensors,ERROR is Error while serializing: IoError(Os { code: 3, kind: NotFound, message: "The system cannot find the path specified." })

Path is clearly there but it cant find it for some reason

**Comment by hako-mikan** [comment]
This error occurs in some reasons.
- The path you specified in your code doesn't exist.
- The path is correct, but the necessary permissions to access or modify it aren't granted.    

check path or permissions.
