### ISSUE TITLE
Using excessive VRAM and failing to unload the model after merging.

### ISSUE THREAD

**Issue by Ketorami** [hako-mikan/sd-webui-supermerger#200]
I have noticed that after each merge, the VRAM usage gradually increases. After merging more than twice, my VRAM becomes full with no available space. As a result, I am unable to use the Merge&Gen function. Normally, after a merge, my VRAM should be around 4-5 GB, but something has caused it to increase to 7 GB without any apparent reason.

I suspect that after merging the models, SuperMerge does not delete the old models stored within the VRAM, resulting in the accumulation of two models within the VRAM. However, I'm not entirely sure about this, as I am not well-versed in coding.

![Screenshot 2023-09-01 042939](https://github.com/hako-mikan/sd-webui-supermerger/assets/101268214/033090af-3140-4f87-b955-0fc3889a7eae)

**Comment by miasik** [comment]
The issue you mentioned is known :-(
https://github.com/hako-mikan/sd-webui-supermerger/pull/189

**Comment by hako-mikan** [comment]
may be fixed
