### ISSUE TITLE
Generated images keep metadata for Denoising strength: 0.7 even when Hires Fix was not used

### ISSUE THREAD

**Issue by Nerogante** [hako-mikan/sd-webui-supermerger#204]
This results in the Hires Fix option getting checked when you Send to txt2img from PNG Info, and you really don't want that checked on accident when Generating from the extension.

![1](https://github.com/hako-mikan/sd-webui-supermerger/assets/45526702/e8aec0a6-10b4-4489-a600-39888b60f80f)

**Comment by hako-mikan** [comment]
Fixed.
