### ISSUE TITLE
The saved model after merge is not usable

### ISSUE THREAD

**Issue by Ketorami** [hako-mikan/sd-webui-supermerger#211]
The model that was saved after merging models is not functioning and has failed. I have attempted to save the model multiple times, but without success. The saved model cannot be used normally, and it has a size of less than 1MB. I don't believe that a saved model would typically have such a small size, so I suspect that there might be something wrong with the model saving function.

![Screenshot 2023-09-03 062610](https://github.com/hako-mikan/sd-webui-supermerger/assets/101268214/4edfac00-005c-4315-a425-af4649c747be)

**Comment by hako-mikan** [comment]
Thanks reporting, fixed.
