### ISSUE TITLE
Calcmodes have become the same

### ISSUE THREAD

**Issue by miasik** [hako-mikan/sd-webui-supermerger#214]
I see that cosA/b and TrainDifference work with the same speed (as fast as only AddNormal worked) and produce the same image.

**Comment by hako-mikan** [comment]
Indeed, it does seem like they're the same. I don't recall making any changes in that area in the recent updates.

**Comment by hako-mikan** [comment]
Based on past data, the difference between CosineA and CosineB seems to be originally small.

**Comment by miasik** [comment]
But it has to be even a little. Anyway, they look the same as normal and
train difference

вс, 3 сент. 2023 г., 11:45 hako-mikan ***@***.***>:

**Comment by miasik** [comment]
Almost immediately, this is impossible
![изображение](https://github.com/hako-mikan/sd-webui-supermerger/assets/1073832/647826b6-11fa-47e5-894a-6e644f1189e1)

**Comment by hako-mikan** [comment]
I had thought that issue was resolved as of yesterday, but does it still occur in the latest version?

**Comment by miasik** [comment]
> I had thought that issue was resolved as of yesterday, but does it still occur in the latest version?

Yes, I'm on [15bcb41a](https://github.com/hako-mikan/sd-webui-supermerger/commit/15bcb41a75566c50d5aa81de057b6fac40d6d360) right now and it seems that I went through all builds since updated a1111 to 1.6

**Comment by hako-mikan** [comment]
Did you try another model?
In your log, 415/415 is unusual value.

**Comment by miasik** [comment]
Well, I have to say Sorry! Looks like my problem is in my new buggy saved model. Calcmodes work well with downloaded models.

**Comment by miasik** [comment]
I as got it, the problem was caused by my newly merged model. In turn it could be caused by #211 (but my model could produce images)
As I see the modes work now as expected, except calculation time.
I see that cosA, cosB and Train difference became ~25% longer. Their time before was ~24 sec and now it's ~30 sec.
Normal weighted sum became much longer. It was almost immediate before a1111 v1.6 and SM updates and 16-18 sec now.
