### ISSUE TITLE
SDXL's lora model cannot be used by the SDXL base model after fusion

### ISSUE THREAD

**Issue by faefgawe** [hako-mikan/sd-webui-supermerger#217]
I am using the A1111 version 1.6 webui. After merging two SDXL lora, I found that it can only be recognized when switching the SD1.5 checkpoint. The SDXL version checkpoint cannot recognize the merged lora.

**Comment by DamienCz** [comment]
+1

**Comment by hako-mikan** [comment]
Fixed.
