### ISSUE TITLE
How to use MBW alpha as X and MBW beta as Y

### ISSUE THREAD

**Issue by Reekin** [hako-mikan/sd-webui-supermerger#22]
If I choose MBW for both X and Y I will get an error.

**Comment by hako-mikan** [comment]
This script has not that feature. But interesting. So I make it.

**Comment by hako-mikan** [comment]
Added. Now you can do that. Please try it out.

**Comment by Reekin** [comment]
> Added. Now you can do that. Please try it out.

Great Job!
