### ISSUE TITLE
XY Plot Gen doesn't use all the settings in the text2image tab

### ISSUE THREAD

**Issue by Reekin** [hako-mikan/sd-webui-supermerger#23]
I toggled Hires.fix and it didn't use it

**Comment by hako-mikan** [comment]
This script does not support Hires.fix. This is a technical issue with the web-ui system that I am trying to address but so far have not been able to do so.

**Comment by hako-mikan** [comment]
Hires.fix is now supported; the txt2img tab setting is not reflected, but can be used by activating it from the supermerger side settings.

**Comment by hako-mikan** [comment]
Currently, hiresfix is available.
