### ISSUE TITLE
Error when trying to create a LORA

### ISSUE THREAD

**Issue by tr7zw** [hako-mikan/sd-webui-supermerger#248]
In the past I often used SuperMerger to create loras after fine-tuning a model using Dreambooth, but after updating the sd.next UI trying to use the "Make LoRA(alpha* A - beta * B)" button gives this exception:

> RuntimeError: Error(s) in loading state_dict for AutoencoderKL:
Missing key(s) in state_dict: "encoder.mid_block.attentions.0.query.weight", "encoder.mid_block.attentions.0.query.bias", "encoder.mid_block.attentions.0.key.weight", "encoder.mid_block.attentions.0.key.bias", "encoder.mid_block.attentions.0.value.weight", "encoder.mid_block.attentions.0.value.bias", "encoder.mid_block.attentions.0.proj_attn.weight", "encoder.mid_block.attentions.0.proj_attn.bias", "decoder.mid_block.attentions.0.query.weight", "decoder.mid_block.attentions.0.query.bias", "decoder.mid_block.attentions.0.key.weight", "decoder.mid_block.attentions.0.key.bias", "decoder.mid_block.attentions.0.value.weight", "decoder.mid_block.attentions.0.value.bias", "decoder.mid_block.attentions.0.proj_attn.weight", "decoder.mid_block.attentions.0.proj_attn.bias".
        Unexpected key(s) in state_dict: "encoder.mid_block.attentions.0.to_key.bias", "encoder.mid_block.attentions.0.to_key.weight", "encoder.mid_block.attentions.0.to_out.0.bias", "encoder.mid_block.attentions.0.to_out.0.weight", "encoder.mid_block.attentions.0.to_query.bias", "encoder.mid_block.attentions.0.to_query.weight", "encoder.mid_block.attentions.0.to_value.bias", "encoder.mid_block.attentions.0.to_value.weight", "decoder.mid_block.attentions.0.to_key.bias", "decoder.mid_block.attentions.0.to_key.weight", "decoder.mid_block.attentions.0.to_out.0.bias", "decoder.mid_block.attentions.0.to_out.0.weight", "decoder.mid_block.attentions.0.to_query.bias", "decoder.mid_block.attentions.0.to_query.weight", "decoder.mid_block.attentions.0.to_value.bias", "decoder.mid_block.attentions.0.to_value.weight".

I assume some Python package is incompatible, but not sure which one/how to fix it.

**Comment by tr7zw** [comment]
Hm made a fresh install of automatic1111 with just SuperMerger and the same issue, tried using older versions of both and it persists. Also tried using kohya_ss, where I get

> RuntimeError: Error(s) in loading state_dict for AutoencoderKL:
        Missing key(s) in state_dict: "encoder.mid_block.attentions.0.to_q.weight",
"encoder.mid_block.attentions.0.to_q.bias", "encoder.mid_block.attentions.0.to_k.weight",
"encoder.mid_block.attentions.0.to_k.bias", "encoder.mid_block.attentions.0.to_v.weight",
"encoder.mid_block.attentions.0.to_v.bias", "decoder.mid_block.attentions.0.to_q.weight",
"decoder.mid_block.attentions.0.to_q.bias", "decoder.mid_block.attentions.0.to_k.weight",
"decoder.mid_block.attentions.0.to_k.bias", "decoder.mid_block.attentions.0.to_v.weight",
"decoder.mid_block.attentions.0.to_v.bias".
        Unexpected key(s) in state_dict: "encoder.mid_block.attentions.0.to_to_k.bias",
"encoder.mid_block.attentions.0.to_to_k.weight", "encoder.mid_block.attentions.0.to_to_q.bias",
"encoder.mid_block.attentions.0.to_to_q.weight", "encoder.mid_block.attentions.0.to_to_v.bias",
"encoder.mid_block.attentions.0.to_to_v.weight", "decoder.mid_block.attentions.0.to_to_k.bias",
"decoder.mid_block.attentions.0.to_to_k.weight", "decoder.mid_block.attentions.0.to_to_q.bias",
"decoder.mid_block.attentions.0.to_to_q.weight", "decoder.mid_block.attentions.0.to_to_v.bias",
"decoder.mid_block.attentions.0.to_to_v.weight".

Which makes it seem like Dreambooth managed to mess up some keys.

**Comment by tr7zw** [comment]
Managed to extract the lora by adding a ``new_path = new_path.replace("to_to_", "to_")`` in kohya_ss model_util during assign_to_checkpoint. Same workaround didn't work for supermerger.

**Comment by hako-mikan** [comment]
I want to resolve the issue, but it's difficult to verify without having a model that produces the error.
Are there models on Civitai or Hugging Face that exhibit a similar error?

**Comment by guahunyo** [comment]
> I want to resolve the issue, but it's difficult to verify without having a model that produces the error. Are there models on Civitai or Hugging Face that exhibit a similar error?

All models seem to have this problem

**Comment by Miczu** [comment]
I probably made a duplicate... I provided link to model I have same issue https://github.com/hako-mikan/sd-webui-supermerger/issues/263

**Comment by hako-mikan** [comment]
Fixed.
