### ISSUE TITLE
Merging mode "Add Difference" not working

### ISSUE THREAD

**Issue by Eljoseto** [hako-mikan/sd-webui-supermerger#25]
Tried to use the "Add difference" merging method but the output is the same as the model A, even when the weight is set to 0.99 for (B-C)

For example, this was generated with AnythingV3 
![00452-DPM++ 2M Karras-30 Steps-Seed 7 0-Hash 27ff17e2d4-(480x640)](https://user-images.githubusercontent.com/29217336/222970273-e71ab265-2693-4bc6-9156-f10f8c548287.png)

And this was generated with add difference, AnythingV3 as model A, dreamlikeDiffusion as model B and stableDiffusion1.5 as model C, alpha at 0.8
![00453-DPM++ 2M Karras-30 Steps-Seed 7 0-Hash baef4ca864-(480x640)](https://user-images.githubusercontent.com/29217336/222970399-83352313-1296-483f-b4e9-8698471d7724.png)

**Comment by hako-mikan** [comment]
Thanks reporting. There was a bug and it was fixed.

**Comment by Eljoseto** [comment]
Thank you for the quick fix!
