### ISSUE TITLE
Models not loading from cache

### ISSUE THREAD

**Issue by kernalkue** [hako-mikan/sd-webui-supermerger#253]
My models no longer seem to get cached by Supermerger. It has made my XYZ plots very slow as the weights are for the models are loaded from file every time.

Was there a change made to compensate for the caching changes in v1.6.0 webui? Do I need to adjust anything?
I have tried reinstalling the extension and resetting all related settings in my ui-config.json

**Comment by hako-mikan** [comment]
If the model cache number in the Settings is set to 1 or more, the cache should be enabled.
In that case, for instance, when the second merge is performed in the XYZ plot, it should display "load from cache."
Is it different in your case?

**Comment by kernalkue** [comment]
![image](https://github.com/hako-mikan/sd-webui-supermerger/assets/7815014/dee04d3d-96c6-4586-8f1a-e96500aa0d5c)
Yes. It used to work fine. I have the above settings and they always "load from file" every time

**Comment by kernalkue** [comment]
Do I need the obsolete setting set?

**Comment by hako-mikan** [comment]
OK. I got it.
You should increase `Checkpoints to cache in RAM`
`Maximum number of checkpoints loaded at same time` is for VRAM.

**Comment by kernalkue** [comment]
Ok I'll try that. In theory ticking the box should create the same effect (1 in vram, 3 in ram), but that doesn't seem to work for supermerger

**Comment by kernalkue** [comment]
> OK. I got it. You should increase `Checkpoints to cache in RAM` `Maximum number of checkpoints loaded at same time` is for VRAM.

Can confirm that this works

**Comment by hako-mikan** [comment]
I'm not using a graphics card equipped with sufficient VRAM, so I can't verify the VRAM options. The options related to RAM work without issues. However, as written in the README, the cache for the web-ui and the cache for supermerger are different.
