### ISSUE TITLE
LoRAマージ指定でのプロンプト型書式のサポート

### ISSUE THREAD

**Issue by JujoHotaru** [hako-mikan/sd-webui-supermerger#256]
いつもお世話になっております。

LoRAの開発中、複数LoRAを合成することもあるのですが、

```
<lora:foo:0.6:lbw=0,1,...0,0> <lora:bar:0.4:lbw=0,0,...2,0>
```

などのように、t2iプロンプトで複数LoRAを階層指定して様子を見つつ生成を繰り返し、最終的なLoRA合成パラメータを探す操作をよくやります。  

そこで、その結果（プロンプトで使った文字列）をLoRAマージの入力指定にそのまま使えるようになると非常に便利だと思いました。  
（`<lora:>`および`lbw=`が文字列に入っていてもエラーにならないようにする、カンマ区切りでない）

実際にはプロンプト指定のパラメータのままで合成してもプロンプト指定の場合と多少結果に違いが出るものですが、そこは仕方ないと考えています。

**Comment by hako-mikan** [comment]
https://github.com/hako-mikan/sd-webui-supermerger/issues/179
でも同様のリクエストがあるので作ろうと思います。しばしお待ちください。

**Comment by hako-mikan** [comment]
機能を追加しました。
`get from prompt`ボタンで読み込めるようになります。

**Comment by JujoHotaru** [comment]
対応ありがとうございました！LoRA開発が非常に楽になりました。

**Comment by JujoHotaru** [comment]
@hako-mikan 

いつもお世話になっております。

以前ご対応いただいた本件なのですが、プロンプトでlbw=を数値直指定（0,1,0,1,...）で記述しているものを取り込むと、SuperMerger側が数値指定に対応していないので動作できなくなります。

これはプロンプト取り込み機能というよりSuperMerger側のLoRA書式指定への要望になるのですが、対応は可能でしょうか…

**Comment by hako-mikan** [comment]
対応しました。1,1,1,1,1,1....のような書式も現在は処理可能です。

**Comment by JujoHotaru** [comment]
ご対応ありがとうございました！便利になりました。
