### ISSUE TITLE
same to Strengthの動作が逆転している…？

### ISSUE THREAD

**Issue by JujoHotaru** [hako-mikan/sd-webui-supermerger#257]
連投ですみません。  
もしかしたら勘違いの可能性もありますので、問題ないと判断したらクローズしてしまってください。

LoRAマージなのですが、最近、same to Strengthをオンにしてマージした結果とオフにしてマージした結果を比べると、オフでマージしたほうが、プロンプトでの強度・階層指定の結果に似た画像が出るケースが多いように感じています。   
特にLoRAを5個・6個など多数まとめてマージした場合に顕著です。

何か不具合でオンオフの意味合いが逆転してしまっているといったことはありえますでしょうか？

**Comment by hako-mikan** [comment]
確かめる方法は簡単で、マイナスのウェイトを指定することで確認できます。
same to Strengthだとマイナスは正常に働き、same to Strengthなしだとマイナスはプラスに変換されます。

**Comment by JujoHotaru** [comment]
情報ありがとうございます。マイナスで実験したところsame to Strengthが意図通りの動作をしていることが確認できました。

ただ、5～6個のLoRAを強度を変えつつ合成する際、やはりsame to Strengthオフのほうがプロンプト指定時（またはそれらをデータモデルにマージして元モデルとの差分抽出でLoRA化したもの）に近い印象で出てくれるようで、これはまた別の問題でしょうか…
ひとまずこちらはクローズいたします。
