### ISSUE TITLE
smoothAdd MT

### ISSUE THREAD

**Issue by Eliont** [hako-mikan/sd-webui-supermerger#258]
Hello and good time of day.

What's difference between regular smoothAdd and smoothAdd MT?

**Comment by hako-mikan** [comment]
The difference is whether multi-threading is used or not. Since smoothAdd operates slowly, smoothAdd MT uses multi-threading. Therefore, it's usually better to use smoothAdd MT.

**Comment by Eliont** [comment]
Thank you.
