### ISSUE TITLE
Feature request: Add cancel merge operation

### ISSUE THREAD

**Issue by Eljoseto** [hako-mikan/sd-webui-supermerger#26]
Hey, this extension is super cool, but there is a problem i'm having rather frecuently

By using the sequential x/y merge, if I select the wrong weights or wrong models, I have to restart the whole service or let it finish for like 10 minutes as it has to merge multiple times.

Would it be possible to add a cancel button to cancel the merging jobs?

Thnaks in advance

**Comment by hako-mikan** [comment]
Ten minutes is certainly a long time. I will think about it.

**Comment by hako-mikan** [comment]
A stop button has been added. If the button is pressed while model A is loading, it will stop before model B is loaded. It can be stopped at any time during the merge.

**Comment by Eljoseto** [comment]
Thank You very much!!
