### ISSUE TITLE
ss_output_name無しのメタデータにしたい

### ISSUE THREAD

**Issue by JujoHotaru** [hako-mikan/sd-webui-supermerger#260]
これまたニッチな要望で恐縮なのですが…

追加いただいたLoRAマージ時のメタデータ出力設定で、Create Newにしてもss_output_nameが書き込まれますが、これが入っていると、LoRAファイルをリネームしてもWebUIでの指定時やCivitAI登録時の内部名などにss_output_nameの値が使われてしまい、実質的な改名ができなくなります。
開発中にコードネームをファイル名として付けたものをリリース時に改名したいことがよくあり、ss_output_nameを出力しない設定にすることができると手間を削減できてよいと思いました。
（今はkohya_ssのmerge_lora.pyで1:0のダミーマージをすることでメタデータを削っています）

**Comment by hako-mikan** [comment]
create new without output_name
を追加しました。

**Comment by JujoHotaru** [comment]
ご対応ありがとうございました。さっそく今後配布予定のLoRAに使用しています。
