### ISSUE TITLE
Adjust settingsが他のcheckpointに影響する

### ISSUE THREAD

**Issue by zzz7xz** [hako-mikan/sd-webui-supermerger#267]
Adjust settingsを調整しマージした後、別のcheckpointを読み込むと、
そのcheckpointにも調整が影響します。

WebUI起動と同時にAdjust settingsを調整しマージしたcheckpointを読み込んだ場合も
そのあとに読み込んだ別のcheckpointに対して調整が影響します。
WebUIを起動しなおすと元に戻ります。

また、起動時に別のcheckpointを読み込んでいた場合は、
Adjust settingを調整しマージしたcheckpointを読み込んでも
調整が反映されていない状態となります。

-- 

追記です。
Prompt内のLoraの有無によって影響するかどうか変わるようです。
Adjust settingsを調整しマージしたcheckpointを読み込んだ状態で
Prompt内にLoraのある出力を一度行うと、
別のcheckpointを読み込んでも影響するようです。

**Comment by hako-mikan** [comment]
調査の結果、これはWeb-UI側のバグだとわかったので、修正依頼を出しておきました。そのうち反映されるかと思います。
https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/13917

**Comment by hako-mikan** [comment]
追記の「Loraの有無によって影響するかどうか変わる」というのが解決のヒントになりました。
ありがとうございます。
