### ISSUE TITLE
Suggestion: Add `CLIP Skip/Reset` options

### ISSUE THREAD

**Issue by Corshi** [hako-mikan/sd-webui-supermerger#27]
Options that in [mbw_each](https://github.com/j4ded/sdweb-merge-block-weighted-gui/tree/master/scripts/mbw_each) part of the [sdweb-merge-block-weighted-gui](https://github.com/j4ded/sdweb-merge-block-weighted-gui).

I makes the tensors aligned correctly.
Do not make it a default/forced, because it will make old recipes not possible anymore.

It can be checked with:
https://github.com/iiiytn1k/sd-webui-check-tensors
or
https://github.com/arenatemp/stable-diffusion-webui-model-toolkit

https://github.com/j4ded/sdweb-merge-block-weighted-gui/blob/master/README_each.md

**Comment by Corshi** [comment]
` radio_position_ids` in this https://github.com/j4ded/sdweb-merge-block-weighted-gui/blob/master/scripts/mbw_each/ui_mbw_each.py

**Comment by hako-mikan** [comment]
Thanks suggestions. I think the problem is that the merge breaks the model. I would like to deal with it. Even now, I avoid merging the parts that are the same as the main web-ui.

**Comment by hako-mikan** [comment]
Added.
