### ISSUE TITLE
XY Plot crash

### ISSUE THREAD

**Issue by Eliont** [hako-mikan/sd-webui-supermerger#275]
`  File "C:\SD\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\xyplot.py", line 690, in draw_grid_annotations
    color_active = ImageColor.getcolor(opts.grid_text_active_color, 'RGB')
  File "C:\SD\stable-diffusion-webui\modules\shared.py", line 581, in __getattr__
    return super(Options, self).__getattribute__(item)
AttributeError: 'Options' object has no attribute 'grid_text_active_color'`

**Comment by hako-mikan** [comment]
It's unclear why this error occurred, but I believe it has been resolved now.
