### ISSUE TITLE
can not load lora

### ISSUE THREAD

**Issue by YDyd11** [hako-mikan/sd-webui-supermerger#280]
I have put the lora in  the /Lora. but when I fresh the webui, I could not find the lora. How can I fix it, whether I have make mistake?

**Comment by hako-mikan** [comment]
Is that LoRA displayed in the txt2img screen's LoRA?

**Comment by YDyd11** [comment]
yes, but It work now, just keep freshing the html or reboot. thank you for your quick reply!:)
