### ISSUE TITLE
Different weight for merging clip and unet?

### ISSUE THREAD

**Issue by dchatel** [hako-mikan/sd-webui-supermerger#281]
When loading a lora, you typically can use different weights for clip and unet, using this syntax: `<lora:name:X:Y>` where `X` is the weight for clip and `Y` is the weight for unet.
I was wondering if it's possible to do this with supermerger "merge lora to checkpoint" feature and if yes how?

**Comment by hako-mikan** [comment]
Use LoRA BLock Weight syntax
`<lora:name:X:Y>`is same to `lora:1:WEIGHT`
`WEIGHT:X,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y,Y`
