### ISSUE TITLE
After update when I try to redim lora I receive this error

### ISSUE THREAD

**Issue by Signorlimone** [hako-mikan/sd-webui-supermerger#286]
change demension to  128
Traceback (most recent call last):
  File "C:\AI\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 374, in lmerge
    sd = merge_lora_models_dim(ln, lr, dim,settings)
TypeError: merge_lora_models_dim() missing 1 required positional argument: 'isv2'
ERROR,Number of Blocks must be 12,17,20,26

**Comment by hako-mikan** [comment]
I thought I had fixed it, but it seems I forgot. Thank you.
