### ISSUE TITLE
System cannot find xyzpresets.json

### ISSUE THREAD

**Issue by silveroxides** [hako-mikan/sd-webui-supermerger#287]
Got the following error:

```The system cannot find the file D:\stable-diffusion-webui\webui\extensions\sd-webui-supermerger\xyzpresets.json```

And neither can I.
I can only find a mention of the file in one line of code in one file on the entire repo too.
Was a file missed when uploading in recent commit?

EDIT: It turns out the extension tried to load the preset by itself even when I was not in the tab after restarting for extension update which gave the error. Seems to be working as intended now. i would suggest adding a placeholder file though so unnecessary errors like this is avoided. [Link to image of the system window that appeared at least](https://i.imgur.com/WmGBq2c.png)

**Comment by hako-mikan** [comment]
I changed the code to disable reading file when file dose not exist.
I avoided placing a placeholder as it may lead to overwriting during updates and other potential issues.
