### ISSUE TITLE
Feature request: Copy/save model config.

### ISSUE THREAD

**Issue by groinge** [hako-mikan/sd-webui-supermerger#290]
Hey, this extension could really benefit for having options for copying config files from checkpoints, like selecting which input checkpoint to copy the config from and the option to save the config alongside the merged model. Currently supermerger will just use the config file from model A when loading the merged model, and it doesn't save a copy for new models.

 I'm asking for this since I'm merging vpred models, which require a config file as otherwise they will just generate noise.

Thanks

**Comment by hako-mikan** [comment]
What is vpred models?

**Comment by Based-Joar** [comment]
> What is vpred models?

https://github.com/mindspore-lab/mindone/blob/master/examples/stable_diffusion_v2/v_prediction.md

Most V2 models have been trained with v prediction. And thus need a config file placed alongside the model to function properly.

Supermerger has no issues merging models like this, it just doesn't copy the config file from one of the input models like a1111's native merger is capable of doing.

**Comment by hako-mikan** [comment]
Added new option `copy config`.
