### ISSUE TITLE
Where the #### is gamma setting?

### ISSUE THREAD

**Issue by silveroxides** [hako-mikan/sd-webui-supermerger#291]
I read through the calcmode_en.md extract chapter perhaps for the eight time now.
I cannot find the UI interface for the gamma parameter that is mentioned in that documentation with the following quote:
```"gamma (γ): Adjusts the selectivity in identifying feature (dis)similarity. High γ (e.g., γ = 10) emphasizes recognizing more similar features as similar. Conversely, low γ (e.g., γ = 0.1) emphasizes recognizing more dissimilar features as dissimilar."```

**Comment by silveroxides** [comment]
> It was difficult to comprehend and fixed it. Gamma can be set in the option items of model merging as option(gamma), and in the case of LoRA, it can be set as gamma(smooth).

I have pulled the update and appreciate the clarity.
There is still the issue about the slider range set since in the calcmode_en.md it says
'High γ (e.g., γ = 10) ' and 'low γ (e.g., γ = 0.1) '
while the slider range being range of '-1' to '2'
```                            opt_value = gr.Slider(label="option(gamma)", minimum=-1.0, maximum=2, step=0.001, value=0.3, interactive=True)```

the proper one would be (unless the slider is used for any other parameters)
```                            opt_value = gr.Slider(label="option(gamma)", minimum=-0.1, maximum=10, step=0.001, value=0.3, interactive=True)```

In addition over on the LoRA tab the block options structure syntax is nothing short of unclear and confusing.
It lacks examples because this is extremely unclear
''LoRAname1:ratio1:Blocks1,LoRAname2:ratio2:Blocks2,...(":blocks" is option, not necessary)''

Here is just one example of several I have tried without any luck what so ever...
'LoRAname:1:BASE:0:IN00:0:IN01:0:IN02:0:IN03:0:IN04:0:IN05:0:IN06:0:IN07:0:IN08:0:IN09:0:IN10:0:IN11:0.25:M00:0:OUT00:0:OUT01:0:OUT02:0:OUT03:0:OUT04:0:OUT05:0:OUT06:0:OUT07:0:OUT08:0:OUT09:0:OUT10:0:OUT11'
giving me this:
`ERROR:Number of Blocks must be 12,17,20,26
merging D:\stable-diffusion-webui\webui\models\Lora\fenris-extractkohyacolossus-231130.safetensors: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
dim: [512, 320, 128], alpha: [512.0, 320.0, 128.0]
merging...
merged model
dim: [512, 320, 128], alpha: [512.0, 320.0, 128.0]`

this 'LoRA:1:BASE'
giving me
`merging D:\stable-diffusion-webui\webui\models\Lora\fenris-extractkohyacolossus-231130.safetensors: [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
dim: [512, 320, 128], alpha: [512.0, 320.0, 128.0]
merging...
merged model
dim: [512, 320, 128], alpha: [512.0, 320.0, 128.0]`

No matter what block I put it always just grabs every block.

**Comment by hako-mikan** [comment]
Syntax is wrong.
Use `LoRAname:1:1,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0`

**Comment by silveroxides** [comment]
> Syntax is wrong. Use `LoRAname:1:1,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0`

Yes I figured that out. Was hoping for a response on the Gamma value sliders. Your guide says values 0.1 to 10 but sliders are in the range -1 to 2.
I actually even was lazy enough to inspect element and force set it to near 10 which was first time addDifference/Extract actually managed to extract true likeness. You should really fix this.

**Comment by hako-mikan** [comment]
OK. I got it and fixed.
