### ISSUE TITLE
Supermerger save current merge failed

### ISSUE THREAD

**Issue by Casper33333** [hako-mikan/sd-webui-supermerger#296]
ERROR: Couldn't saved:D:\ai\sd-webui-aki-v4.4\models\Stable-diffusion\65623.safetensors,ERROR is You are trying to save a non contiguous tensor: `model.diffusion_model.input_blocks.0.0.weight` which is not allowed. It either means you are trying to save tensors which are reference of each other in which case it's recommended to save only the full tensors, and reslice at load time, or simply call `.contiguous()` on your tensor to pack it before saving.

**Comment by Casper33333** [comment]
It can be saved as a ckpt file, and an error will be reported if safetensors are checked.

**Comment by dmower16** [comment]
I've been having the same problem. Seems like whenever I do a weighted merge with random block weights it causes this. It would be nice to find a way to fix this problem, or at least know how to prevent it

**Comment by hako-mikan** [comment]
Fixed.
Thanks @wkpark for PR.
