### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Deathawaits4** [hako-mikan/sd-webui-supermerger#306]
Hello!

we really need a better documentation of some features, because im really ripping out my hair here, especially with the lora block weight merge. 

1. We need some kind of log(or information where the log is) if the block merge was successfull, the console does not state any information what has been merged with what weight. As this: Test_266:1:ALL0.5 starts the merge, but also this: Test_266:1:dfsadfsfds, which is not even a preset and its difficult to determine if there is a difference in result. So please add some kind of information on what blocks have been with which weight. This would be extremely awesome

2. How do we set our own weights? I have read in another thread, that you need to "create and save a own preset".. makes sense, but how? There is no documentation on how to do that, no button, no saving option, no file. 

the guide states: LoRAname1:ratio1:1,0,0,0,1,1,1,1,1,1,1,1,0,0,0,0,0

but this clearly isnt working

This tool is great, but i can only use a small portion of it, because i dont understand how to use it.

Thanks!

**Comment by silveroxides** [comment]
> Please note, that i am specifically talking about the lora merge tab.

It uses same syntax as [sd-webui-lora-block-weight](https://github.com/hako-mikan/sd-webui-lora-block-weight)
If you install that extension in addition to supermerger you will find a new section below image generation in txt2img where you can see the various presets. and the various valid blocks to specify is mentioned at that repo.
Here is an image giving a bit over overview aswell. Nice to have as reference.
[imgur-LoRA-Blocks](https://i.imgur.com/rbmSvxJ.png)

**Comment by Deathawaits4** [comment]
Thanks, this somewhat clarified most questions
