### ISSUE TITLE
Error in SD.NEXT after update to 6a4893d

### ISSUE THREAD

**Issue by ThePixelDiffusionPirate** [hako-mikan/sd-webui-supermerger#328]
Since I work on an older AMD graphics card (Win11, 5700XT) I have turned off many things, can this be related?
SD.NEXT Stable Build [9bf08c5]

-------------------------
12:32:01-136960 ERROR    executing callback:

                         C:\Users\TestBuild\Diffusion\TheSDNEXT\automatic\extensions\sd-webui-supermerger\scripts\s

                         upermerger.py ui_tabs_callback: AttributeError

╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮

│ C:\Users\TestBuild\Diffusion\TheSDNEXT\automatic\modules\script_callbacks.py:184 in ui_tabs_callback            │

│                                                                                                                      │

│   183 │   │   │   t0 = time.time()                                                                                   │

│ ❱ 184 │   │   │   res += c.callback() or []                                                                          │

│   185 │   │   │   timer(t0, c.script, 'ui_tabs')                                                                     │

│                                                                                                                      │

│ C:\Users\TestBuild\Diffusion\TheSDNEXT\automatic\extensions\sd-webui-supermerger\scripts\supermerger.py:409 in  │

│ on_ui_tabs                                                                                                           │

│                                                                                                                      │

│    408 │   │   │   │   │                                                                                             │

│ ❱  409 │   │   │   │   │   mgallery = output_panel.gallery                                                           │

│    410 │   │   │   │   │   mgeninfo = output_panel.generation_info                                                   │

╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

AttributeError: 'tuple' object has no attribute 'gallery'

12:32:01-254180 DEBUG    Read: file="C:\Users\TestBuild\Diffusion\TheSDNEXT\automatic\html\extensions.json"

                         json=346 bytes=203917 time=0.000

12:32:01-845834 DEBUG    Extension list: processed=330 installed=8 enabled=4 disabled=4 visible=330 hidden=0

12:32:02-026433 INFO     Local URL: http://127.0.0.1:7860/

12:32:02-026433 DEBUG    Gradio functions: registered=956

12:32:02-026433 INFO     Initializing middleware

12:32:02-036478 DEBUG    Creating API

12:32:02-175012 ERROR    executing callback:

                         C:\Users\TestBuild\Diffusion\TheSDNEXT\automatic\extensions\sd-webui-supermerger\scripts\G

                         enParamGetter.py app_started_callback: TypeError

╭───────────────────────────────────────── Traceback (most recent call last) ──────────────────────────────────────────╮

│ C:\Users\TestBuild\Diffusion\TheSDNEXT\automatic\modules\script_callbacks.py:133 in app_started_callback        │

│                                                                                                                      │

│   132 │   │   │   t0 = time.time()                                                                                   │

│ ❱ 133 │   │   │   c.callback(demo, app)                                                                              │

│   134 │   │   │   timer(t0, c.script, 'app_started')                                                                 │

│                                                                                                                      │

│ C:\Users\TestBuild\Diffusion\TheSDNEXT\automatic\extensions\sd-webui-supermerger\scripts\GenParamGetter.py:90   │

│ in get_params_components                                                                                             │

│                                                                                                                      │

│    89 │   │   │   │   │   fn=smergegen,                                                                              │

│ ❱  90 │   │   │   │   │   inputs=[*components.msettings,components.esettings1,*components.genp                       │

│    91 │   │   │   │   │   outputs=[components.submit_result,components.currentmodel]                                 │

╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

TypeError: Value after * must be an iterable, not NoneType

12:32:02-195085 DEBUG    Scripts setup: ['X/Y/Z Grid:0.007']
-----------------------

**Comment by hako-mikan** [comment]
Fixed.
