### ISSUE TITLE
Extension incompatible with SD-Webui-Replacer

### ISSUE THREAD

**Issue by mykeehu** [hako-mikan/sd-webui-supermerger#335]
Recently I found an interesting problem. 
When SD-Webui-Replacer and SuperMerger are enabled together, the interface does not work when the WEBUI is first loaded, i.e. you cannot click on buttons and the lists do not update (e.g. the Extensions tab does not load). I just tested all my extensions and the interface is only good when Replacer or Supermerger is disabled. 
If both are on, the error occurs. I wrote about it here on the Replacer page:
https://github.com/light-and-ray/sd-webui-replacer/issues/36

**Comment by hako-mikan** [comment]
Are you enabling the option to automatically open the browser upon launch?

If you have other extensions (like sd-webui-prompt-all-in-one) installed simultaneously, enabling the option to automatically open the browser upon launch can cause instability in its operation. It's likely an issue with Gradio, so it might be difficult to fix. Please disable that option and use it.
https://github.com/hako-mikan/sd-webui-supermerger?tab=readme-ov-file#knowon-issues%E6%97%A2%E7%9F%A5%E3%81%AE%E5%95%8F%E9%A1%8C
