### ISSUE TITLE
feature request: export lora list w/dimensions (after calculating) to CSV

### ISSUE THREAD

**Issue by ride5k** [hako-mikan/sd-webui-supermerger#339]
this doesn't seem like it would be hard to implement, but i am no coder.  i find myself going through a lot of copy paste formatting to keep a list of loras with dimensions handy, and this would save a lot of time.

**Comment by aleph23** [comment]
or json

**Comment by hako-mikan** [comment]
Added feature.
Considering the use of sorting in Excel, it seems best to save the file in CSV format. The file is saved in the SuperMerger directory under the name loradims.csv.
