### ISSUE TITLE
adjust sliders (in out out2 contrast etc)

### ISSUE THREAD

**Issue by Enferlain** [hako-mikan/sd-webui-supermerger#342]
Are these adjusting some individual layers known to be responsible for the described result? Like detail/noise etc? How did you find out which layers they are, and does it apply to sdxl?

I can't find the names of the layers in the code :(

**Comment by Enferlain** [comment]
how do you modify them exactly and couldn't you do the same with other layers?

**Comment by hako-mikan** [comment]
That is indeed a very challenging issue.  
These parameters are not deliberately specified by humans but are numerical values accumulated during the learning process. Therefore, it is difficult to explain theoretically why they are as they are, and I think it is also challenging to configure them effectively.

**Comment by Enferlain** [comment]
Yeah it seems a bit tough. I've been trying to run bayesian optimization (set values, gen image, score image, repeat) with them. It might be v-pred related, but the detail adjustments aren't as good as I remember them from earlier sdxl models, and it's too easy to fall into the darker=better problem. And the color adjustments are pretty destructive for color accuracy, but it's cool that it can be done

![xyz_grid-0000-2951461378](https://github.com/user-attachments/assets/06a93f45-a032-4600-b093-455b00528c6e)
