### ISSUE TITLE
Extract from two LoRAs always reproduces first LoRA

### ISSUE THREAD

**Issue by belladoreai** [hako-mikan/sd-webui-supermerger#345]
It seems that no matter what settings I use, the result from "extract from two LoRAs" ends up being just LoraB as it is. I don't understand why this happens. I'm guessing I have some setting incorrectly somewhere? Can someone provide an example of how to use this feature properly?

Here's an example of how I'm trying to use it (I have tried many settings, result always same):

- alpha 1
- beta 1
- gamma 0.1
- text input field: loraB:1,loraC:1

Shouldn't these settings produce the most dissimilar features from loraC? But even with these settings the end result is just loraB.

**Comment by hako-mikan** [comment]
Thanks reporting, fixed.

**Comment by hako-mikan** [comment]
@belladoreai 
Fixed.

**Comment by belladoreai** [comment]
Now when I click the update button, I no longer get an error, but the list of LoRAs renders as an empty list (even though there are a bunch of LoRAs).

![loras-on-disk](https://github.com/hako-mikan/sd-webui-supermerger/assets/135602125/7a0ec17b-70cf-4527-94e1-89af68360fc9)

**Comment by hako-mikan** [comment]
When launched, does it display a list of LoRAs on disk for which dims have not been calculated?

**Comment by belladoreai** [comment]
> When launched, does it display a list of LoRAs on disk for which dims have not been calculated?

Yes.

**Comment by hako-mikan** [comment]
Thanks, fixed.

**Comment by belladoreai** [comment]
Now the update button seems to work, but it no longer lists the dims (or whatever information was previously listed) after each LoRA. The list now only shows the name for each LoRA. Not sure if this is intended or not. I don't see any errors.

**Comment by hako-mikan** [comment]
Does the calculate button not work

**Comment by belladoreai** [comment]
> Does the calculate button not work?

Ah, that works. Thanks! I think previously the update button was doing that work, not sure.

**Comment by belladoreai** [comment]
I made some test merges and I can confirm that I'm now at least seeing different results with different parameters. So I believe it's now working, although the results are a little bit funny, but maybe that's just because I don't fully understand how these merges work and what the results are supposed to look like.

Thanks for the fixes.
