### ISSUE TITLE
Temp files during merge default to system drive

### ISSUE THREAD

**Issue by Derjyn** [hako-mikan/sd-webui-supermerger#348]
During merging tasks, temporary files are being created on the system/OS drive by default. This is an issue, as some merges can take many, many gigs of temp space, and it's not at all uncommon for system drives to have minimal and optimized space constraints.

Exposing a setting for where these temporary files are stored should be a priority.

**Comment by hako-mikan** [comment]
Isn't that a setting on the system side?
I wonder if it could be addressed by changing the temp folder that Python deals with through the OS settings.
