### ISSUE TITLE
Question: What is Alpha, beta and Gamma in LoRa Merge?

### ISSUE THREAD

**Issue by DenisKen** [hako-mikan/sd-webui-supermerger#349]
![image](https://github.com/hako-mikan/sd-webui-supermerger/assets/15076521/98f154ef-7a5a-470b-a793-3085b386bd05)

**Comment by hako-mikan** [comment]
https://github.com/hako-mikan/sd-webui-supermerger/blob/main/calcmode_en.md#extracting-dissimilar-features-from-differential-models
