### ISSUE TITLE
Author, can you support 1.8? There are serious errors now

### ISSUE THREAD

**Issue by kakaxixx** [hako-mikan/sd-webui-supermerger#351]
Author, can you support 1.8? There are serious errors now

**Comment by aleph23** [comment]
Are you using a freshly installed a1111 env without modifications (like Forge)?  What are the errors?  I'm asking because the extension works for me under a clean a1111 1.8 install, but does not when I apply Forge.  (And because error reports really need to come with more information than just 'there are serious errors now.')

**Comment by kakaxixx** [comment]
Traceback (most recent call last):
  File "H:\forge\system\python\lib\site-packages\gradio\routes.py", line 488, in run_predict
    output = await app.get_blocks().process_api(
  File "H:\forge\system\python\lib\site-packages\gradio\blocks.py", line 1431, in process_api
    result = await self.call_function(
  File "H:\forge\system\python\lib\site-packages\gradio\blocks.py", line 1103, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "H:\forge\system\python\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "H:\forge\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "H:\forge\system\python\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "H:\forge\system\python\lib\site-packages\gradio\utils.py", line 707, in wrapper
    response = f(*args, **kwargs)
  File "H:\forge\webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 738, in pluslora
    theta_0 = newpluslora(theta_0,filenames,lweis,names, isxl,isv2, keychanger)
  File "H:\forge\webui\extensions\sd-webui-supermerger\scripts\mergers\pluslora.py", line 809, in newpluslora
    nets.load_networks(names)
  File "H:\forge\webui\extensions-builtin\Lora\networks.py", line 65, in load_networks
    for a, b, c in zip(networks_on_disk, unet_multipliers, te_multipliers):
TypeError: 'NoneType' object is not iterable

**Comment by kakaxixx** [comment]
A111 same

**Comment by aleph23** [comment]
Which Supermerger function are you attempting when you get the error?  Do you get the same error with ALL supermerger functions?  

Try:
- If your SD server is running, shut it down.
- Disable all extensions, except for /Extensions-Builtin and Supermerger.  You can simply move all folders from /extensions to another location outside of /extensions, then copy the Supermerger directory back (or don't move it when you move the others)
- Restart a1111/forge server and see if you are still getting the same error.  Try more than one function of Supermerger (merging lora, model analysis, different model merge maths (cosine_A, block weighted, etc)).  Also, sometimes after receiving one error, it's necessary to restart the server before trying another task.


Shutdown and re-start your server

**Comment by celluuuu** [comment]
> Which Supermerger function are you attempting when you get the error? Do you get the same error with ALL supermerger functions?
> 
> Try:
> 
> * If your SD server is running, shut it down.
> * Disable all extensions, except for /Extensions-Builtin and Supermerger.  You can simply move all folders from /extensions to another location outside of /extensions, then copy the Supermerger directory back (or don't move it when you move the others)
> * Restart a1111/forge server and see if you are still getting the same error.  Try more than one function of Supermerger (merging lora, model analysis, different model merge maths (cosine_A, block weighted, etc)).  Also, sometimes after receiving one error, it's necessary to restart the server before trying another task.

I don't see the Supermerger extension in the tabs at all, I've disabled all other extensions except for /Extensions-Builtin and Supermerger but still it's not showing. I've restarted multiple times but no idea why it's still not showing

**Comment by aleph23** [comment]
Do you get a an error message in console while trying to load that says something about "**OutputPanel**'?  (_it's been a while since I had this error, so I don't remember the exact text of the message)_

**Comment by hako-mikan** [comment]
Same to https://github.com/hako-mikan/sd-webui-supermerger/issues/334,fixed.
