### ISSUE TITLE
missing tab

### ISSUE THREAD

**Issue by LozyLL** [hako-mikan/sd-webui-supermerger#36]
Supermerger is loaded but the tab is somehow missing, i was just using it earlier today.
![missing tab](https://user-images.githubusercontent.com/126636908/227837698-65bad90c-b7be-4590-80f2-69fc37564094.PNG)
And got this report
![15FO9ZDSLAS6 L42O`HVK9D](https://user-images.githubusercontent.com/126636908/227838562-4f32d7a1-ee33-4ef0-8278-65c45ad15746.png)

**Comment by hako-mikan** [comment]
Thanks reporting, fixed.
