### ISSUE TITLE
SD-WebUI v1.8 (dev) - Can't merge LoRa to checkpoint

### ISSUE THREAD

**Issue by Derjyn** [hako-mikan/sd-webui-supermerger#360]
When attempting to merge a LoRa into a checkpoint, the following error is thrown:

```
\sd-webui-supermerger\scripts\mergers\pluslora.py", line 703, in pluslora
    dname = dname + "+"+n
            ~~~~~~^~~~~
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

It would seem that the dropdowns for "Checkpoint Tuned" and "Checkpoint Original" are messed up? When selecting a model in the tuned dropdown, this issue doesn't occur. When selecting the original dropdown, error occurs. When selecting same model in both, the issue doesn't occur.

When just merging in a LoRa to a checkpoint, logically we would be selecting our model from the "original" dropdown... But I could have that totally mixed up!

**Comment by hako-mikan** [comment]
There were other opinions that it was confusing, so I changed it to the notation of Model A, B.
