### ISSUE TITLE
ckpt-dir is ignored when saving ckpt

### ISSUE THREAD

**Issue by vekitan55** [hako-mikan/sd-webui-supermerger#363]
Super Merger refers to A1111's ckpt-dir and lora-dir for ckpt and LoRA, but ckpt-dir is ignored only when saving ckpt and is written to A1111's model folder (LoRA is lora-dir). dir). It's not a particular problem, but it's probably a bug.

Super MergerはckptやLoRAの参照にはA1111のckpt-dirやlora-dirを参照するが，ckptの保存時だけckpt-dirが無視され，A1111のmodelフォルダに書き込みが行われる（LoRAはlora-dirに格納される）。とくに困ってはいないのだが，おそらくバグだろう。

**Comment by hako-mikan** [comment]
Fixed, thanks.
