### ISSUE TITLE
Merge & Generate in Suggestion on the right side image display frame.(右側の画像表示枠についての提案)

### ISSUE THREAD

**Issue by muooon** [hako-mikan/sd-webui-supermerger#364]
お世話になってます。右枠にある画像表示部を画面表示に合わせて上下に移動できませんか？

現在のA1111生成画面は右枠画像表示部は画面表示の上下に合わせて枠そのものも一緒に上へ下へと移動し生成画面の下部にあるオプション設定のパラメーターを調整しながら生成画面も確認できます。(説明下手でわかりづらかったらごめんなさい)
supermerger でも同じようになり "Adjust" の設定を変えながらお試し画像を確認できたら便利そうだなと思っています。右枠に Generate ボタンも配置変えする等も必要だろうと思いますが可能なら画面表示に追従して画像枠の表示も自動で移動して欲しいです。

ご多忙と思いますがぜひ一度ご検討ください。

**Comment by hako-mikan** [comment]
できるようになりましたー。

**Comment by muooon** [comment]
ご対応に感謝です！ものすごくいいです！こんなに早く改修されるなんて嬉しいです！
もしお時間あればもうひとつ、Merge, Merge & Gen, Gen, Stop,の４ボタンを画像表示領域の下に移動できませんか？
これが叶えば｢Adjust｣設定をポチポチしながら生成したり修正したり…これができれば調整しやすくなります。勝手ばかりで申し訳ないのですがこちらもぜひご検討ください。
もうひとつ。手放せない拡張機能を本当にありがとうございます。ご対応にも感謝です。

**Comment by hako-mikan** [comment]
できるようになりましたー。

**Comment by muooon** [comment]
ああ！なるほど両側にボタンを配置したんですね!! 控えめに言って｢最高！｣です。
この度は利用者からの提案を快く引き受けてくださり感謝しかありません。
今後のご活躍を祈ります。本当にありがとうございました。
