### ISSUE TITLE
Supermerger extension not showing in tabs in A1111 

### ISSUE THREAD

**Issue by celluuuu** [hako-mikan/sd-webui-supermerger#365]
I've tried to disable all other extensions but it's still not showing. Any idea what else I could try? I'm using runpod secure cloud and Jupyter notebook. Python 3.10.12.

**Comment by hako-mikan** [comment]
May be fixed.

**Comment by pedx78** [comment]
not working with latest 1111 or forge.

which version of diffusers, transformers  are required ?

```version: v1.10.1  •  python: 3.10.6  •  torch: 2.1.2+cu121  •  xformers: N/A  •  gradio: 3.41.2, windows```
