### ISSUE TITLE
Should check for `sklearn` instead of `scikit-learn` in install.py

### ISSUE THREAD

**Issue by SLAPaper** [hako-mikan/sd-webui-supermerger#37]
Now, 'sklearn' is automatically installed in launch.

_Originally posted by @hako-mikan in https://github.com/hako-mikan/sd-webui-supermerger/issues/30#issuecomment-1479792948_

Should check for `sklearn` instead of `scikit-learn` in install.py

![image](https://user-images.githubusercontent.com/7543632/228401800-c946e297-9dae-4262-a90b-299088254c45.png)

For now the extension will try install scikit-learn every time no matter if already installed

**Comment by hako-mikan** [comment]
Thanks! fixed
