### ISSUE TITLE
Can't extract LoRA from ckpt or safetensors correctly.

### ISSUE THREAD

**Issue by Gmsdmjmix** [hako-mikan/sd-webui-supermerger#38]
the LoRA has been created,but doesn't work.help,please.

here is the record:

To create a public link, set `share=True` in `launch()`.
Startup time: 22.8s (import gradio: 8.5s, import ldm: 1.2s, other imports: 2.4s, list extensions: 1.2s, setup codeformer: 0.1s, load scripts: 2.1s, load SD checkpoint: 6.4s, create ui: 0.6s, gradio launch: 0.3s).
make LoRA start
loading SD model : E:\novelai-webui-aki-v3\models\Stable-diffusion\Anything-v4.5-vae-fp16-vae-swapped.ckpt
loading u-net: < All keys matched successfully>
loading vae: < All keys matched successfully>
loading text encoder: < All keys matched successfully>
loading SD model : E:\novelai-webui-aki-v3\models\Stable-diffusion\chilloutmix_NiPrunedFp32Fix.safetensors
loading u-net:< All keys matched successfully>
loading vae: < All keys matched successfully>
loading text encoder:  < All keys matched successfully>
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 0 modules.
create LoRA for Text Encoder: 72 modules.
create LoRA for U-Net: 0 modules.
calculating by svd

enable LoRA for text encoder
enable LoRA for U-Net
LoRA has 216 weights.
Loading extracted LoRA weights:  < All keys matched successfully>
LoRA weights are saved to: E:\novelai-webui-aki-v3\models\Lora\lora_chilloutmix_NiPrunedFp32Fix-Anything-v4.5-vae-fp16-vae-swapped.safetensors

**Comment by hako-mikan** [comment]
If it is successfully saved, does that mean that the generated image is wrong?

**Comment by fayer1688** [comment]
> If it is successfully saved, does that mean that the generated image is wrong?

I have the same problem, when I upgrade diffusers version it works fine

**Comment by hako-mikan** [comment]
Since there are many people reporting this issue, I decided to discuss it elsewhere.
Discuss the rest here.
https://github.com/hako-mikan/sd-webui-supermerger/discussions/52
