### ISSUE TITLE
no errors but not working

### ISSUE THREAD

**Issue by dynatron832** [hako-mikan/sd-webui-supermerger#382]
hi

i wanted to try something with live model merging and cant bring the merger to work. i simply go to the extension manager and chose supermerger to install. after its done WebUI gets an reset. and there the problems begin. it is not that i can see any error but supermerger hangs half of WebUI. what did i mean ? now ...if i start WebUI there i loads ...the web browser jumps on and presents me the known WebUI. but no matter what i enter as soon i hit the generate button nothing happens. no errors no crash. the console is still quiet and the webui looks like responding. i can switch the tabs ...the only thing what is looking wrong is the fact that the exension tab is not showing the installed script list. instead it say´s loding. no matter how long. and no matter how many times i press generate nothing happend. and thats without even touching the supermerger tab. i can restart webui and without errors it do´s it. but even after loading the script list is on loading and generating something not working. after i delete the supermerger script folder and start webui everything is working as it should be. ive been using v1.9.3 and also testing the merger on 1.8.0 and its doing the same. no script list and dont generate something.

one little extra. because i wanted to live merge models i also found sd-webui-model-mixer and it produces the same error. no script list and generate dont respond.

**Comment by hako-mikan** [comment]
Known issues.
Did you install any other extensions such as sd-webui-prompt-all-in-one?
https://github.com/hako-mikan/sd-webui-supermerger/tree/main?tab=readme-ov-file#knowon-issues%E6%97%A2%E7%9F%A5%E3%81%AE%E5%95%8F%E9%A1%8C
