### ISSUE TITLE
DIT models support ?

### ISSUE THREAD

**Issue by ReyJ94** [hako-mikan/sd-webui-supermerger#383]
Any planned support for DIT models such as Pixart sigma and hunyuan dit ?

**Comment by TomLucidor** [comment]
Not just Flux, AuraFlow, Hunyuan, but also PixArt!? Yeah they need to get on it as well

**Comment by hako-mikan** [comment]
Now support flux in forge.

**Comment by hako-mikan** [comment]
This script depends on the Web-UI itself, so once the main UI is supported, other models are expected to be supported as well. At this point, it's unclear whether SD3 will improve, so it's pending.

**Comment by TomLucidor** [comment]
@hako-mikan skip SD3 probably, but AuraFlow could be promising

**Comment by ReyJ94** [comment]
Automatic 1111 seems to be a repo that does not get much updates, at lot of people are switching to forge ui. I tried the extension on forge ui and it does not work. Any possibility to make it work there as well ?

**Comment by TomLucidor** [comment]
@ReyJ94 they should be compatible with one another

**Comment by ReyJ94** [comment]
maybe now it could be, but for a long time it was not. supermerger did not show in the top bar after installation.
