### ISSUE TITLE
save all images from XYZ in a grid?

### ISSUE THREAD

**Issue by boldoran** [hako-mikan/sd-webui-supermerger#387]
is it possible to add a function so it saves all the images in a grid that are generated with XYZ plot?
it would be usefull to compare multiple images of the same generation against others.

unless im extremely stupid but I havent found this option in the past 8 months

**Comment by jmblsmit** [comment]
If you use auto1111 check your txt2img-grids folder.

**Comment by boldoran** [comment]
it just posts the first seed, first images into the grid, lets say i make batches of 4 images, i only get the first image in the grid, the other 3 arnt there. they are in the image folder, but not in the grid.

**Comment by hako-mikan** [comment]
Fixed.

**Comment by boldoran** [comment]
It does save all the images, in an xy grid. So theyre seperate grids.

Is it possible to save them in a big xyz grid?
Or am i doing it wrong?

This already is an improvement tho. Thanks!

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by hako-mikan** [comment]
When combining everything into a large grid, the image size may become too large and violate various restrictions, so it should be avoided.

**Comment by boldoran** [comment]
> When combining everything into a large grid, the image size may become too large and violate various restrictions, so it should be avoided.

thats true, but sometimes in smaller batches it would be handy to set them side by side.
but this still works, and i thank you for it!
ill use xnview orsomething to view them side by side :)
