### ISSUE TITLE
Merge SDXL does not work

### ISSUE THREAD

**Issue by padjake** [hako-mikan/sd-webui-supermerger#388]
list index out of range. 
Usually, I use Forge. Then I downloaded A1111 just to try the supermerger, but the results were the same.
Yes, I deleted and reinstalled. It doesn't work either.
It still works properly with SD 1.5. I have no idea how to solve it.

Forge
![Screenshot (373)](https://github.com/user-attachments/assets/b70e584d-5154-459c-80ff-cf8385e8d6a6)

A1111
![Screenshot (375)](https://github.com/user-attachments/assets/5d35e720-28f3-48c3-bee7-597443b630cc)

**Comment by hako-mikan** [comment]
Same to #371
The XL LoRAs have merged so far have not caused any issues.
Could you let me know which LoRAs you are trying to merge that result in an error?
Also, please share the version of diffusers you are using.
