### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'model_name' in mergers.py

### ISSUE THREAD

**Issue by axsddlr** [hako-mikan/sd-webui-supermerger#41]
## Describe the bug
An AttributeError is raised when running the stable-diffusion-webui application. The error states that the 'NoneType' object has no attribute 'model_name'.

## To Reproduce

1. Run the stable-diffusion-webui application
2. Perform a specific action (e.g., try to merge models)
3. Observe the traceback

## Error message
```
Traceback (most recent call last):
  ...
  File "D:\Programs\gitrepos\PROJS\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 273, in load_model_weights_m
    sd_model_name = checkpoint_info.model_name
AttributeError: 'NoneType' object has no attribute 'model_name'
```

## Additional context
This issue seems to occur within the load_model_weights_m function in the mergers.py file, and it might be related to a missing or improperly loaded checkpoint.

**Comment by hako-mikan** [comment]
This error occurs when selected model is not exist.   
Dose this error occur in only supermerger?
Did you tried web-ui CheckpointMerger?

**Comment by hako-mikan** [comment]
I found the cause. The problem seems to occur when trying to merge again with the same model. Resolved. Thanks.
