### ISSUE TITLE
Featutre Request: increase batch size for gens

### ISSUE THREAD

**Issue by hypernewb** [hako-mikan/sd-webui-supermerger#42]
Are we only allowed to make one image per gen? it would be good if it recognized batch sizes and let us generate a lot so we can easily compare.

**Comment by hako-mikan** [comment]
Batch size can now be specified.

**Comment by wilhelmw201** [comment]
changing the batch size does not work with MBW on my side

**Comment by hako-mikan** [comment]
Do you mean you set batch size in XY plot mode?
XY plot dose not support batch size now.
I'm going to make it now.

**Comment by hako-mikan** [comment]
added
