### ISSUE TITLE
Feature Request: Negatively blockmerge

### ISSUE THREAD

**Issue by ryukra** [hako-mikan/sd-webui-supermerger#48]
I tried negatively merging my model with 1.5 and it removes realistic and unwanted stuff:

https://media.discordapp.net/attachments/1065193870616440882/1094649934378172488/tmphs4cbiah.png
Looks pretty good, can we have this as block merge?

**Comment by hako-mikan** [comment]
You can still do it.
Without slider, input values directly.
Or, negative values are also inputted in presets.

**Comment by ryukra** [comment]
OH! I still had the old UI without tabs/lora and got errors when inserting negative values.. even if I always installed updates.
