### ISSUE TITLE
Colab crashes when extracting Lora

### ISSUE THREAD

**Issue by gilroff** [hako-mikan/sd-webui-supermerger#51]
Colab has 12gb ram and 15gb Vram. Is that enough?

**Comment by hako-mikan** [comment]
This may not be sufficient. If the full model is used, this script alone uses 8 GB of memory.

Since there are many people reporting this issue, I decided to discuss it elsewhere.
Discuss the rest here.
https://github.com/hako-mikan/sd-webui-supermerger/discussions/52
