### ISSUE TITLE
ImportError: cannot import name 'TYPESEG' from 'scripts.mergers.mergers'

### ISSUE THREAD

**Issue by axsddlr** [hako-mikan/sd-webui-supermerger#55]
### Description

When attempting to load the script 'supermerger.py' located in the directory 'D:\Programs\gitrepos\PROJS\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\', an error occurred. The error message states that the import of 'TYPESEG' from 'scripts.mergers.mergers' was unsuccessful. This error occurred in line 14 of 'supermerger.py'.

### Steps to Reproduce

1. Attempt to load 'supermerger.py' in the directory 'D:\Programs\gitrepos\PROJS\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\'.
2. Observe the error message 'ImportError: cannot import name 'TYPESEG' from 'scripts.mergers.mergers' (stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\mergers.py)'.

### Expected Behavior

The 'supermerger.py' script should load without any errors.

### Actual Behavior

The script failed to load and raised an ImportError.

**Comment by hako-mikan** [comment]
Did you restart webui.bat?

**Comment by axsddlr** [comment]
> Did you restart webui.bat?

yes i did, re-ran everything
