### ISSUE TITLE
TypeError: argument 'metadata': 'NoneType' object cannot be converted to 'PyString'

### ISSUE THREAD

**Issue by Kuyoh-ai** [hako-mikan/sd-webui-supermerger#58]
save_metadata=Falseの場合以下の箇所でTypeErrorとなります。
sd-webui-supermerger\scripts\mergers\model_util.py", line 700, in savemodel
    safetensors.torch.save_file(state_dict, fname, metadata=metadata)

mergers/mergers.py line 110,
`    metadata = {"format": "pt", "sd_merge_models": {}, "sd_merge_recipe": None}`
にて空のdictとNoneが設定されていることが原因かと思われます。

mergers/mergers.py line 110,を
`    metadata = {"format": "pt"}`
に修正し、line 340, 341を
```
        metadata["sd_merge_recipe"] = json.dumps(merge_recipe)
        metadata["sd_merge_models"] = {}
```
とすることで動作を確認できましたので、修正よろしくお願いいたします。

**Comment by NathanSamurai** [comment]
I get the same error

**Comment by hako-mikan** [comment]
@Kuyoh-ai 
ありがとうございます。早速修正しました。

@NathanSamurai 
Fixed.
