### ISSUE TITLE
Bug: When using the Calculation Mode cosine, the result is completely opposite to that of normal.

### ISSUE THREAD

**Issue by Kuyoh-ai** [hako-mikan/sd-webui-supermerger#60]
連日かつ日本語で失礼いたします。

以下画像の通り、比率の計算がnormalとcosineで逆になっていると思われます。

### Weight sum
- normal
![Weight_sum_normal](https://user-images.githubusercontent.com/129640257/232468638-b70f9dfd-1775-43fd-a228-06fd062ce457.png)
- cosine
![Weight_sum_cosine](https://user-images.githubusercontent.com/129640257/232468683-bad5f670-2b9c-4d80-8ba4-dae6cbbb858f.png)

### MBW
- normal
![MBW_normal](https://user-images.githubusercontent.com/129640257/232468776-a5694655-d086-4814-857f-0bd132afc275.png)
- cosine
![MBW_cosine](https://user-images.githubusercontent.com/129640257/232468823-fdc0a3fb-69d9-4653-8457-ecf131750ae2.png)

### Triple Sum (beta = 0.1固定)
- normal
![Triple_sum_normal](https://user-images.githubusercontent.com/129640257/232472951-eef1ebb7-ba6b-4266-a465-5776e89b4149.png)
- cosine
![Triple_sum_cosine](https://user-images.githubusercontent.com/129640257/232472971-d6be9332-f604-428c-aaa8-f10bb4040d80.png)

ソースを読み解く力がなく具体的な修正方法を報告できず申し訳ございません。
よろしくお願いします。

**Comment by hako-mikan** [comment]
ありがとうございます。
これは私も認識していました。
今このコードを書いた方と新しい実装につて議論しているので次回アップデート時にはなおるかもです。

**Comment by recoilme** [comment]
Sorry, i don't know (Japan?)
But probably alpha shifted in another direction
[Now](https://github.com/hako-mikan/sd-webui-supermerger/blob/main/scripts/mergers/mergers.py#L309):
```
k = k - current_alpha
theta_0[key] = theta_0[key] * (1 - k) + theta_1[key] * k
```
[In losslessmix](https://github.com/recoilme/losslessmix/blob/master/weightedsim.py#L53)
```
            k = k - args.s
            a[key] = a[key] * k + b[key] * (1 - k)
```
Probably, k = k + current_alpha, but i'm not sure

I swap weights A and B in original alghorithm, sorry for this mess..

**Comment by hako-mikan** [comment]
@recoilme 
Thanks for your help, however, a new mode of optimization was proposed for both models individually, which was adopted.
https://github.com/hako-mikan/sd-webui-supermerger/blob/main/calcmode_en.md

@Kuyoh-ai 
モデルA/Bどちらかを選んで最適化する方式を新たに導入したので問題は解決したかと思います。
https://github.com/hako-mikan/sd-webui-supermerger/blob/main/calcmode_en.md

**Comment by Kuyoh-ai** [comment]
@hako-mikan 
非常に迅速な対応ありがとうございます。
また、非常に有効なlosslessmixを考案・実装した関係者の方々にも非常に感謝いたします。
--
Thank you very much for your prompt response. Additionally, I am extremely grateful to those involved in devising and implementing the highly effective losslessmix.
