### ISSUE TITLE
your plugin conflicts with sd-dynamic-prompts the plugin

### ISSUE THREAD

**Issue by ggwazh** [hako-mikan/sd-webui-supermerger#61]
Hello author, your plugin conflicts with [sd-dynamic-prompts](https://github.com/adieyal/sd-dynamic-prompts) the plugin, which will cause the wild-card of the sd-dynamic-prompts plugin to disappear from the wild-card manager tab. I hope you can improve your plugin, thank you very much!

**Comment by hako-mikan** [comment]
I' trying to solve this problem but there is no errors.
It may take some time.

**Comment by hako-mikan** [comment]
I found the cause and fixed.
