### ISSUE TITLE
Diffusers 0.15.0 issue

### ISSUE THREAD

**Issue by warnerchavescdp** [hako-mikan/sd-webui-supermerger#63]
The curent version is not compatible with diffusers 0.15.0, extracting a Lora no longer works. Current workaround is to force a pip downgrade to diffusers 0.14.0

**Comment by Trevor-Z** [comment]
> The curent version is not compatible with diffusers 0.15.0, extracting a Lora no longer works. Current workaround is to force a pip downgrade to diffusers 0.14.0

What are the arguments for downgrading?

**Comment by hako-mikan** [comment]
I have tried with diffusers 0.10.2 and 0.14.0 and both seem to work.
I also installed diffusers 0.15.0 and got the same error.

@warnerchavescdp 
However, I would like to quit enforcing it because of the relationship with other repositories. I will only mention this in the README.
Thanks.
