### ISSUE TITLE
Error when trying to make LoRA from checkpoint in local SD

### ISSUE THREAD

**Issue by Trevor-Z** [hako-mikan/sd-webui-supermerger#70]
I'm trying to follow these instructions to make a LoRA, using Auto1111:

https://github.com/hako-mikan/sd-webui-supermerger/issues/13#issuecomment-1445131450

And I get this error:

![Screenshot 2023-04-29 181452](https://user-images.githubusercontent.com/13950948/235324875-e4a5fd62-ffa1-4f1c-aaba-6d393f3a40f3.png)

What does it mean?

**Comment by CyberLykan** [comment]
See #63
Seems to be an issue with Diffusers versions past 0.14.0.
Current workaround is to downgrade diffusers to 0.14.0.

**Comment by Trevor-Z** [comment]
> See #63 Seems to be an issue with Diffusers versions past 0.14.0. Current workaround is to downgrade diffusers to 0.14.0.

Does downgrading affect anything?

**Comment by hako-mikan** [comment]
This script using Kohya's script and that tested in diffusers 0.10.2.
https://github.com/kohya-ss/sd-scripts#about-requirementstxt
