### ISSUE TITLE
Calcmodes: ValueError: could not convert string to float

### ISSUE THREAD

**Issue by axsddlr** [hako-mikan/sd-webui-supermerger#71]
**Description:**
```
Traceback (most recent call last):
  File "D:\Programs\gitrepos\PROJS\stable-diffusion-webui\venv\lib\site-packages\gradio\routes.py", line 394, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Programs\gitrepos\PROJS\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 1075, in process_api
    result = await self.call_function(
  File "D:\Programs\gitrepos\PROJS\stable-diffusion-webui\venv\lib\site-packages\gradio\blocks.py", line 884, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Programs\gitrepos\PROJS\stable-diffusion-webui\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Programs\gitrepos\PROJS\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\Programs\gitrepos\PROJS\stable-diffusion-webui\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\Programs\gitrepos\PROJS\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\xyplot.py", line 52, in numanager
    result,currentmodel,xyimage,a,b,c= sgenxyplot(xtype,xmen,ytype,ymen,esettings,
  File "D:\Programs\gitrepos\PROJS\stable-diffusion-webui\extensions\sd-webui-supermerger\scripts\mergers\xyplot.py", line 307, in sgenxyplot
    _ , currentmodel,modelid,theta_0,_=smerge(weights_a_in,weights_b_in, model_a,model_b,model_c, float(alpha),float(beta),mode,calcmode,
ValueError: could not convert string to float: ''
```

## Issue:
The program encounters a ValueError when trying to convert a string to a float in the `sgenxyplot` function.

## Steps to reproduce:
1. use mbw values in Sequential XY Merge and Generation
2. Observe the error when the program reaches the `sgenxyplot` function.

## Expected behavior:
The program should be able to convert the string values to floats without encountering a ValueError.

Possible solution:
Check the variables involved in the conversion and add a condition to handle cases when the string is empty or not convertible to a float.
```

**Comment by hako-mikan** [comment]
It seems to me that there are blanks, etc. mixed in with the alpha or beta values such as "0.25, , 0.5" and "0.25,0.5,". I tried to make it work with inputs in such values.

**Comment by axsddlr** [comment]
this is result of using mbw values

**Comment by miasik** [comment]
It seems to me that I have the the same.
Is there a way to avoid it?

> Stage 1/2:   1%|█▌                                                                                                                                                      | 12/1143 [00:00<?, ?it/s]
> Traceback (most recent call last):
>   File "e:\SD\automatic1111\venv\lib\site-packages\gradio\routes.py", line 399, in run_predict
>     output = await app.get_blocks().process_api(
>   File "e:\SD\automatic1111\venv\lib\site-packages\gradio\blocks.py", line 1299, in process_api
>     result = await self.call_function(
>   File "e:\SD\automatic1111\venv\lib\site-packages\gradio\blocks.py", line 1022, in call_function
>     prediction = await anyio.to_thread.run_sync(
>   File "e:\SD\automatic1111\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
>     return await get_asynclib().run_sync_in_worker_thread(
>   File "e:\SD\automatic1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
>     return await future
>   File "e:\SD\automatic1111\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
>     result = context.run(func, *args)
>   File "E:\SD\automatic1111\extensions\sd-webui-supermerger\scripts\mergers\xyplot.py", line 52, in numanager
>     result,currentmodel,xyimage,a,b,c= sgenxyplot(xtype,xmen,ytype,ymen,esettings,
>   File "E:\SD\automatic1111\extensions\sd-webui-supermerger\scripts\mergers\xyplot.py", line 316, in sgenxyplot
>     _ , currentmodel,modelid,theta_0,_=smerge(weights_a_in,weights_b_in, model_a,model_b,model_c, float(alpha),float(beta),mode,calcmode,
>   File "E:\SD\automatic1111\extensions\sd-webui-supermerger\scripts\mergers\mergers.py", line 307, in smerge
>     dr = float(dr)
> ValueError: could not convert string to float: ''

**Comment by hako-mikan** [comment]
If you are inserting empty line feeds you may get a similar error.
