### ISSUE TITLE
Two M00 columns in elemental_en.md

### ISSUE THREAD

**Issue by miasik** [hako-mikan/sd-webui-supermerger#77]
As I see in the table here [elemental_en.md](https://github.com/hako-mikan/sd-webui-supermerger/blob/main/elemental_en.md) there are two different M00 columns.
Is it OK?

**Comment by hako-mikan** [comment]
its OK.
M00 seems to have multiple in_layers's etc.

**Comment by hako-mikan** [comment]
model.diffusion_model.middle_block.0.emb_layers.1.bias
model.diffusion_model.middle_block.0.emb_layers.1.weight
model.diffusion_model.middle_block.0.in_layers.0.bias
model.diffusion_model.middle_block.0.in_layers.0.weight
model.diffusion_model.middle_block.0.in_layers.2.bias
model.diffusion_model.middle_block.0.in_layers.2.weight
model.diffusion_model.middle_block.0.out_layers.0.bias
model.diffusion_model.middle_block.0.out_layers.0.weight
model.diffusion_model.middle_block.0.out_layers.3.bias
model.diffusion_model.middle_block.0.out_layers.3.weight
model.diffusion_model.middle_block.1.norm.bias
model.diffusion_model.middle_block.1.norm.weight
model.diffusion_model.middle_block.1.proj_in.bias
model.diffusion_model.middle_block.1.proj_in.weight
model.diffusion_model.middle_block.1.proj_out.bias
model.diffusion_model.middle_block.1.proj_out.weight
model.diffusion_model.middle_block.1.transformer_blocks.0.attn1.to_k.weight
model.diffusion_model.middle_block.1.transformer_blocks.0.attn1.to_out.0.bias
model.diffusion_model.middle_block.1.transformer_blocks.0.attn1.to_out.0.weight
model.diffusion_model.middle_block.1.transformer_blocks.0.attn1.to_q.weight
model.diffusion_model.middle_block.1.transformer_blocks.0.attn1.to_v.weight
model.diffusion_model.middle_block.1.transformer_blocks.0.attn2.to_k.weight
model.diffusion_model.middle_block.1.transformer_blocks.0.attn2.to_out.0.bias
model.diffusion_model.middle_block.1.transformer_blocks.0.attn2.to_out.0.weight
model.diffusion_model.middle_block.1.transformer_blocks.0.attn2.to_q.weight
model.diffusion_model.middle_block.1.transformer_blocks.0.attn2.to_v.weight
model.diffusion_model.middle_block.1.transformer_blocks.0.ff.net.0.proj.bias
model.diffusion_model.middle_block.1.transformer_blocks.0.ff.net.0.proj.weight
model.diffusion_model.middle_block.1.transformer_blocks.0.ff.net.2.bias
model.diffusion_model.middle_block.1.transformer_blocks.0.ff.net.2.weight
model.diffusion_model.middle_block.1.transformer_blocks.0.norm1.bias
model.diffusion_model.middle_block.1.transformer_blocks.0.norm1.weight
model.diffusion_model.middle_block.1.transformer_blocks.0.norm2.bias
model.diffusion_model.middle_block.1.transformer_blocks.0.norm2.weight
model.diffusion_model.middle_block.1.transformer_blocks.0.norm3.bias
model.diffusion_model.middle_block.1.transformer_blocks.0.norm3.weight
model.diffusion_model.middle_block.2.emb_layers.1.bias
model.diffusion_model.middle_block.2.emb_layers.1.weight
model.diffusion_model.middle_block.2.in_layers.0.bias
model.diffusion_model.middle_block.2.in_layers.0.weight
model.diffusion_model.middle_block.2.in_layers.2.bias
model.diffusion_model.middle_block.2.in_layers.2.weight
model.diffusion_model.middle_block.2.out_layers.0.bias
model.diffusion_model.middle_block.2.out_layers.0.weight
model.diffusion_model.middle_block.2.out_layers.3.bias
model.diffusion_model.middle_block.2.out_layers.3.weight
