### ISSUE TITLE
Question: The results are not the same depending on the calculation mode.

### ISSUE THREAD

**Issue by Tktw** [hako-mikan/sd-webui-supermerger#79]
`alpha=0` or `ALL_A`, but the result is not the same depending on `Calcutation Mode`.
`normal` `cosineA` `cosineB`
Is this the intended result?

**Comment by hako-mikan** [comment]
Intended. Currently, even with alpha=0, the ratio is varied by calculating the similarity in cosine mode, so the results will vary depending on the mode.
However, it would be better to allow the user to choose whether or not to calculate the similarity even for alpha=0. Thank you for your question.

**Comment by Tktw** [comment]
Thank you for your answer.
I was a little confused, but I actually just wanted to clarify, so no problem! :smile:
