### ISSUE TITLE
disable Tags being added to image names

### ISSUE THREAD

**Issue by Username69992872** [hako-mikan/sd-webui-supermerger#8]
Somehow generated images have tags in the image name. How to disable? (images generated by clicking the "Gen" button)

**Comment by hako-mikan** [comment]
The image file naming rules follow the settings of the web-ui main unit. This can be changed from setting - Saving images/grid - Images filename pattern in the web-ui main settings.

Do you mean that the name given to the image is different when you press the Gen button and when you press the Generate button on the txt2img tab?
