### ISSUE TITLE
Errors after merging LoRA to checkpoint

### ISSUE THREAD

**Issue by Trevor-Z** [hako-mikan/sd-webui-supermerger#83]
If I merge some LoRA's to a checkpoint, and then try to Merge&Gen the resulting checkpoint to another one using cosineA, cosineB, or sometimes tensor, I get these errors:

![cosineA](https://github.com/hako-mikan/sd-webui-supermerger/assets/13950948/39196684-3108-4952-850b-ef3a80582e58)
![cosineB](https://github.com/hako-mikan/sd-webui-supermerger/assets/13950948/5b23a70f-0363-43fa-bc11-952d50dab56c)

**Comment by hako-mikan** [comment]
What is the name of the checkpoint where the LoRA was merged?
It appears that it cannot find the new checkpoint.
