### ISSUE TITLE
Suddenly all LoRA extractions yield corrupted results (rainbow blotchy outputs) - Worked a few days ago (Update: Default Alpha/Beta values no longer 1 after A1111 update - Default now set to values that create bad models)

### ISSUE THREAD

**Issue by CCpt5** [hako-mikan/sd-webui-supermerger#91]
Edit/ Update: Seems as thought the default / launch values set for Alpha & Beta in the LoRA tab are not set to 1 as they were in earlier versions of A1111. Instead they're set to .5 and .25 which can produce bad LoRA files for those who don't usually adjust those values. Worth examining why those defaults have changed to prevent confusion as it caused me. If this is something exclusive to my setup - apologies. Thanks!!

-----

Any ideas on why I could be getting the following type of output on images generated w/ LoRAs I've extracted using Supermeger? I only started having issues yesterday after it worked perfect. I've double checked my diffusers version and that's fine. It seems like Merging itself works fine, but for some reason when I extract a LoRA using the LoRA tab w/ A as being my Dreambooth trained ckpt, and B being the SD 1.5 cpkt that it was trained on, I end up w/ the below results when using the trigger words.

I'm not sure what changed aside form upgrading to A1111 Ver 1.3 and adding a few extensions that I don't believe are related.

Edit: I tried using a developer version of A1111 and that does seem to work. I removed all extensions aside from Supermerger on my main install and still had the same problem. 

Could this be related to the update to A1111 pushed last week (To 1.3)? Or perhaps due to the update to Pytorch to 2.0? I'm pretty sure I had Pytorch 2.0 installed while it was working earlier though. 

Thanks for any suggestions!

![tmpwj0e9uv6](https://github.com/hako-mikan/sd-webui-supermerger/assets/37972078/94dc6ff4-4def-44c2-817e-ee34c2288e3a)

![1515](https://github.com/hako-mikan/sd-webui-supermerger/assets/37972078/cc690d03-4cc7-46a4-b763-fb72529642ae)

**Comment by hako-mikan** [comment]
Thanks reporting, in updating to 1.3, some settings may be changed.
Fixed.
