### ISSUE TITLE
LoRA extractions errors: Error still exist for diffuser 0.16.0 and default value for Alpha & Beta is set to 0.5 and 0.25

### ISSUE THREAD

**Issue by lolvivianli** [hako-mikan/sd-webui-supermerger#92]
I understand CCpt5 mentioned the default Alpha & Beta value changes on "https://github.com/hako-mikan/sd-webui-supermerger/issues/91#issue-1731148685", I did encounter the same problem with the following system setting:
![image](https://github.com/hako-mikan/sd-webui-supermerger/assets/127157052/a32630fa-7cb6-4784-89e4-1fff57820f10)
I'm not sure why the value changed since it also happened in my previous laptop, which the A1111 Webui was last updated on May 27 on that laptop.
The 0.5 and 0.25 settings did create a defect Lora that generated images like this, could the default value be changed after restarting of UI? since it's kinda annoying to reset the value every time >.<
![image](https://github.com/hako-mikan/sd-webui-supermerger/assets/127157052/bff01ede-abd6-499a-a32b-8655de159080)

In addition, I understand another problem has been addressed somewhere, which is the default installed diffuser 0.16.0 will give an error when extracting Lora, will this ever get fixed in the future?

Other than that, great extension and thank you hako for your time and effort in making this extension :D. This is one of my fav extensions!

**Comment by hako-mikan** [comment]
Fixed. Thanks.
